(()=>{
const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
const clamp=(v,a,b)=>Math.max(a,Math.min(b,v)),lerp=(a,b,t)=>a+(b-a)*t,smooth=(a,b,t)=>{t=clamp((t-a)/(b-a),0,1);return t*t*(3-2*t)};
const REDUCE=matchMedia('(prefers-reduced-motion:reduce)').matches,COARSE=matchMedia('(pointer:coarse)').matches,MOBILE=innerWidth<700;
const nav=$('#nav'),burger=$('#burger'),sections=$$('.sec'),links=$$('.nav-links a');
const io=new IntersectionObserver(es=>es.forEach(e=>e.isIntersecting&&e.target.classList.add('rv-in')),{threshold:.12,rootMargin:'0px 0px -6%'});$$('[data-rv]').forEach(el=>io.observe(el));
burger?.addEventListener('click',()=>{const o=document.body.classList.toggle('nav-open');burger.setAttribute('aria-expanded',String(o))});links.forEach(a=>a.addEventListener('click',()=>document.body.classList.remove('nav-open')));
sections.forEach((s,i)=>{const b=document.createElement('button');b.innerHTML='<i></i>';b.title=s.id;b.setAttribute('aria-label',s.id);b.onclick=()=>scrollTo({top:s.offsetTop-24,behavior:REDUCE?'auto':'smooth'});$('#rail')?.appendChild(b)});const dots=$$('#rail button');
function state(){const mid=innerHeight*.46;let best=0,bd=1e9;sections.forEach((s,i)=>{const r=s.getBoundingClientRect(),d=Math.abs(r.top+r.height*.43-mid);if(d<bd){bd=d;best=i}});dots.forEach((d,i)=>d.classList.toggle('on',i===best));links.forEach(a=>a.classList.toggle('on',a.hash==='#'+sections[best].id));nav?.classList.toggle('stuck',scrollY>40)}addEventListener('scroll',state,{passive:true});state();
function fgStages(){const pairs=$$('.sec .fg').map(stage=>({section:stage.closest('.sec'),stage})).filter(x=>x.section),sky=$('#fg-sky');if(!pairs.length||!sky)return;const ratios=new Map(pairs.map(p=>[p.section,0])),homes=new WeakMap(pairs.map(p=>[p.stage,p.section])),timers=new WeakMap();let current=null;const park=s=>{const h=homes.get(s);if(h&&s.parentNode!==h)h.insertBefore(s,h.firstChild)},retire=s=>{if(!s||s===current)return;clearTimeout(timers.get(s));s.classList.remove('fg-active');if(REDUCE)return park(s);s.classList.add('fg-retiring');timers.set(s,setTimeout(()=>{s.classList.remove('fg-retiring');park(s)},820))},activate=s=>{if(!s||s===current)return;clearTimeout(timers.get(s));s.classList.remove('fg-retiring');if(s.parentNode!==sky){sky.appendChild(s);void s.offsetWidth}s.classList.add('fg-active');const old=current;current=s;retire(old)};const ob=new IntersectionObserver(es=>{es.forEach(e=>ratios.set(e.target,e.isIntersecting?e.intersectionRatio:0));let n=pairs[0];pairs.forEach(p=>{if((ratios.get(p.section)||0)>(ratios.get(n.section)||0))n=p});if((ratios.get(n.section)||0)>0)activate(n.stage)},{rootMargin:'-12% 0px',threshold:[0,.12,.32,.55]});pairs.forEach(p=>ob.observe(p.section))}fgStages();
const cursor=$('#cursor');if(cursor&&!COARSE&&matchMedia('(hover:hover)').matches){let x=innerWidth/2,y=innerHeight/2,tx=x,ty=y;addEventListener('pointermove',e=>{tx=e.clientX;ty=e.clientY},{passive:true});(function f(){x=lerp(x,tx,.18);y=lerp(y,ty,.18);cursor.style.transform=`translate3d(${x}px,${y}px,0)`;requestAnimationFrame(f)})()}
if(!window.THREE){document.body.classList.add('no-webgl');return}
const renderer=new THREE.WebGLRenderer({canvas:$('#gl'),antialias:true,alpha:false,powerPreference:'high-performance'});renderer.setPixelRatio(Math.min(devicePixelRatio,MOBILE?1.15:1.45));renderer.setSize(innerWidth,innerHeight,false);renderer.outputEncoding=THREE.sRGBEncoding;renderer.toneMapping=THREE.ACESFilmicToneMapping;renderer.toneMappingExposure=.82;renderer.shadowMap.enabled=true;renderer.shadowMap.type=THREE.PCFSoftShadowMap;
const scene=new THREE.Scene();scene.background=new THREE.Color(0x03080b);scene.fog=new THREE.FogExp2(0x071218,.016);const camera=new THREE.PerspectiveCamera(40,innerWidth/innerHeight,.08,240);const WORLD={uT:{value:0},fg:[],machine:new THREE.Group()};window.__FARO_QA__={ready:false,world:'single-webgl-v4',plates:false,registered:true};
function rng(seed=1){let a=seed>>>0;return()=>{a|=0;a=a+0x6D2B79F5|0;let t=Math.imul(a^a>>>15,1|a);t=t+Math.imul(t^t>>>7,61|t)^t;return((t^t>>>14)>>>0)/4294967296}}
function cvs(w,h){const c=document.createElement('canvas');c.width=w;c.height=h;return c}function tx(c,rep=[1,1]){const t=new THREE.CanvasTexture(c);t.wrapS=t.wrapT=THREE.RepeatWrapping;t.repeat.set(...rep);t.encoding=THREE.sRGBEncoding;t.anisotropy=8;return t}
function weather(seed,base){const S=512,c=cvs(S,S),x=c.getContext('2d'),r=rng(seed);x.fillStyle=base;x.fillRect(0,0,S,S);for(let i=0;i<10500;i++){const v=105+r()*110,a=.015+r()*.11;x.fillStyle=`rgba(${v},${v+3},${v+2},${a})`;x.fillRect(r()*S,r()*S,.5+r()*2.7,.5+r()*3.8)}for(let i=0;i<260;i++){const rust=r()>.55;x.fillStyle=rust?`rgba(91,49,28,${.02+r()*.11})`:`rgba(224,231,220,${.01+r()*.07})`;x.beginPath();x.ellipse(r()*S,r()*S,2+r()*24,1+r()*8,r()*Math.PI,0,Math.PI*2);x.fill()}for(let i=0;i<36;i++){x.strokeStyle=`rgba(31,42,41,${.035+r()*.065})`;x.lineWidth=.5+r()*1.5;x.beginPath();let y=r()*S;x.moveTo(0,y);for(let k=1;k<10;k++){y+=(r()-.5)*13;x.lineTo(k*S/9,y)}x.stroke()}return tx(c,[2.3,2.3])}
const stoneMap=weather(12,'#858b87'),ironMap=weather(38,'#222727'),rockMap=weather(71,'#101719');
const stone=new THREE.MeshStandardMaterial({map:stoneMap,color:0x919792,roughness:.95,metalness:0}),stoneDim=new THREE.MeshStandardMaterial({map:stoneMap,color:0x626966,roughness:.97,metalness:0}),iron=new THREE.MeshStandardMaterial({map:ironMap,color:0x302c29,roughness:.64,metalness:.72}),ironDark=new THREE.MeshStandardMaterial({map:ironMap,color:0x101617,roughness:.57,metalness:.8}),rock=new THREE.MeshStandardMaterial({map:rockMap,color:0x172126,roughness:.95,metalness:.01}),brass=new THREE.MeshStandardMaterial({color:0x74542f,roughness:.42,metalness:.91}),brassHi=new THREE.MeshStandardMaterial({color:0xa67d45,roughness:.28,metalness:.95}),glass=new THREE.MeshPhysicalMaterial({color:0x9bb7b3,transparent:true,opacity:.20,transmission:.84,thickness:.4,ior:1.46,roughness:.06,depthWrite:false}),prism=new THREE.MeshPhysicalMaterial({color:0xb7d1cc,transparent:true,opacity:.38,transmission:.76,thickness:.62,ior:1.48,roughness:.025,depthWrite:false});
const skyMat=new THREE.ShaderMaterial({side:THREE.BackSide,depthWrite:false,uniforms:{uDawn:{value:0}},vertexShader:`varying vec3 vP;void main(){vP=position;gl_Position=projectionMatrix*modelViewMatrix*vec4(position,1.);}`,fragmentShader:`uniform float uDawn;varying vec3 vP;void main(){float h=clamp(normalize(vP).y*.5+.5,0.,1.);vec3 night=mix(vec3(.034,.070,.086),vec3(.006,.016,.026),smoothstep(.2,1.,h));float bank=smoothstep(.25,.62,h)*(1.-smoothstep(.60,.92,h));night+=vec3(.018,.027,.030)*bank;vec3 dawn=mix(vec3(.40,.40,.36),vec3(.16,.27,.31),h);gl_FragColor=vec4(mix(night,dawn,uDawn),1.);}`});scene.add(new THREE.Mesh(new THREE.SphereGeometry(160,32,20),skyMat));
const seaMat=new THREE.ShaderMaterial({uniforms:{uTime:WORLD.uT,uDawn:{value:0}},vertexShader:`uniform float uTime;varying float vH;varying vec3 vP;void main(){vec3 p=position;float h=sin(p.x*.24+uTime*.28)*.16+sin(p.y*.15-uTime*.20)*.12+sin((p.x+p.y)*.08+uTime*.11)*.09+sin(p.x*.72-p.y*.43+uTime*.47)*.025;p.z+=h;vH=h;vP=p;gl_Position=projectionMatrix*modelViewMatrix*vec4(p,1.);}`,fragmentShader:`uniform float uDawn;varying float vH;varying vec3 vP;void main(){float crest=smoothstep(.08,.32,vH),line=pow(max(0.,sin(vP.x*.31+vP.y*.10)*.5+.5),24.);vec3 n=mix(vec3(.006,.025,.037),vec3(.045,.102,.123),crest*.48)+vec3(.15,.17,.16)*line*crest*.18;vec3 d=mix(vec3(.075,.14,.16),vec3(.25,.28,.26),crest);gl_FragColor=vec4(mix(n,d,uDawn),1.);}`});const sea=new THREE.Mesh(new THREE.PlaneGeometry(210,210,96,96),seaMat);sea.rotation.x=-Math.PI/2;sea.position.y=-2.75;scene.add(sea);
const hemi=new THREE.HemisphereLight(0x6c8490,0x020709,.28);scene.add(hemi);const moon=new THREE.DirectionalLight(0x91aeb9,1.0);moon.position.set(-13,18,8);moon.castShadow=true;moon.shadow.mapSize.set(1024,1024);scene.add(moon);const houseLight=new THREE.PointLight(0xd78342,2.7,18,2);houseLight.position.set(-3.8,1.4,.9);scene.add(houseLight);const opticWarm=new THREE.PointLight(0xefad65,5.5,14,2);opticWarm.position.set(0,9.15,-1.45);scene.add(opticWarm);const opticRim=new THREE.SpotLight(0x91bfcc,5.8,20,Math.PI/7,.45,1.2);opticRim.position.set(5,11,4);opticRim.target.position.set(0,9.15,-1.2);scene.add(opticRim,opticRim.target);
/* Continuous headland: no pile of visible icosahedra. */
const landGeo=new THREE.PlaneGeometry(42,34,70,58),lp=landGeo.attributes.position,lr=rng(501);for(let i=0;i<lp.count;i++){const x=lp.getX(i),y=lp.getY(i),d=Math.sqrt(x*x*.45+y*y*.18),ridge=1.05*Math.exp(-d*.08)+Math.sin(x*.31)*.28+Math.sin(y*.25+x*.11)*.20+(lr()-.5)*.16;lp.setZ(i,ridge)}landGeo.computeVertexNormals();const land=new THREE.Mesh(landGeo,rock);land.rotation.x=-Math.PI/2;land.position.set(0,-2.55,-1.3);land.receiveShadow=true;scene.add(land);
const world=new THREE.Group();world.position.z=-1.2;scene.add(world),tower=new THREE.Group();world.add(tower);
/* Registered tower: only five masonry courses; gallery begins exactly where body ends. */
for(let i=0;i<5;i++){const h=1.18,y=2.55+i*1.12,r=1.72-i*.075,seg=new THREE.Mesh(new THREE.CylinderGeometry(r-.07,r,h,72,4),i<2?stoneDim:stone);seg.position.y=y;seg.rotation.y=(i%2?1:-1)*.014;seg.castShadow=seg.receiveShadow=true;tower.add(seg);const seam=new THREE.Mesh(new THREE.TorusGeometry(r,.014,5,72),stoneDim);seam.rotation.x=Math.PI/2;seam.position.y=y-h*.5;tower.add(seam)}
const baseRing=new THREE.Mesh(new THREE.CylinderGeometry(1.82,1.9,.18,72),stoneDim);baseRing.position.y=.78;tower.add(baseRing);const door=new THREE.Mesh(new THREE.BoxGeometry(.72,1.58,.09),ironDark);door.position.set(0,1.52,1.72);tower.add(door);
for(let i=0;i<4;i++){const a=.45+i*.95,y=2.45+i*1.12,ap=new THREE.Mesh(new THREE.BoxGeometry(.42,.66,.075),ironDark);ap.position.set(Math.sin(a)*(1.60-i*.07),y,Math.cos(a)*(1.60-i*.07));ap.lookAt(0,y,0);tower.add(ap);const sill=new THREE.Mesh(new THREE.BoxGeometry(.60,.08,.20),stoneDim);sill.position.copy(ap.position);sill.position.y-=.38;sill.lookAt(0,sill.position.y,0);tower.add(sill)}
const house=new THREE.Group(),hb=new THREE.Mesh(new THREE.BoxGeometry(6.1,2.25,4.1),stoneDim);hb.position.set(-3.35,.05,.3);hb.castShadow=hb.receiveShadow=true;house.add(hb);const roof=new THREE.Mesh(new THREE.CylinderGeometry(3.9,3.9,.3,4),ironDark);roof.rotation.y=Math.PI/4;roof.scale.z=.72;roof.position.set(-3.35,1.35,.3);house.add(roof);for(let i=0;i<3;i++){const lit=i===1,w=new THREE.Mesh(new THREE.BoxGeometry(.66,.80,.075),new THREE.MeshStandardMaterial({color:lit?0x694224:0x061012,emissive:lit?0x633012:0,emissiveIntensity:lit?.8:0,roughness:.34}));w.position.set(-4.8+i*1.48,.10,2.40);house.add(w)}world.add(house);
const galleryY=7.47,gallery=new THREE.Mesh(new THREE.CylinderGeometry(2.08,2.08,.17,72),ironDark);gallery.position.y=galleryY;tower.add(gallery);for(let i=0;i<40;i++){const a=i/40*Math.PI*2,p=new THREE.Mesh(new THREE.CylinderGeometry(.017,.017,.74,6),ironDark);p.position.set(Math.cos(a)*1.96,galleryY+.37,Math.sin(a)*1.96);tower.add(p)}for(const y of [galleryY+.25,galleryY+.58]){const r=new THREE.Mesh(new THREE.TorusGeometry(1.96,.021,6,80),ironDark);r.rotation.x=Math.PI/2;r.position.y=y;tower.add(r)}
const lanternY=8.62,lantern=new THREE.Group(),room=new THREE.Mesh(new THREE.CylinderGeometry(1.62,1.62,1.72,32,1,true),glass);room.position.y=lanternY;lantern.add(room);for(let i=0;i<16;i++){const a=i/16*Math.PI*2,p=new THREE.Mesh(new THREE.BoxGeometry(.026,1.75,.04),ironDark);p.position.set(Math.cos(a)*1.63,lanternY,Math.sin(a)*1.63);p.rotation.y=-a;lantern.add(p)}const lower=new THREE.Mesh(new THREE.CylinderGeometry(1.70,1.70,.10,64),ironDark);lower.position.y=7.77;lantern.add(lower);const crown=new THREE.Mesh(new THREE.CylinderGeometry(1.70,1.70,.10,64),ironDark);crown.position.y=9.49;lantern.add(crown);const cap=new THREE.Mesh(new THREE.ConeGeometry(1.78,.84,48),ironDark);cap.position.y=10.00;lantern.add(cap);tower.add(lantern);
/* Stair ends below gallery, never intersects the lantern room. */
const stair=new THREE.Group();for(let i=0;i<43;i++){const a=i*.36,y=1.08+i*.14,r=.98,step=new THREE.Mesh(new THREE.BoxGeometry(1.08,.048,.31),ironDark);step.position.set(Math.cos(a)*r,y,Math.sin(a)*r);step.rotation.y=-a+.16;stair.add(step);if(i%2===0){const p=new THREE.Mesh(new THREE.CylinderGeometry(.015,.015,.54,6),iron);p.position.set(Math.cos(a)*1.41,y+.27,Math.sin(a)*1.41);stair.add(p)}}tower.add(stair);
/* Fresnel shares lantern origin. */
const machine=WORLD.machine;machine.position.set(0,lanternY,0);world.add(machine),lens=new THREE.Group();machine.add(lens);for(let i=0;i<15;i++){const r=.19+i*.074,ring=new THREE.Mesh(new THREE.TorusGeometry(r,.020,10,96),prism);ring.position.z=.02+i*.0015;lens.add(ring)}const drum=new THREE.Mesh(new THREE.CylinderGeometry(.80,.80,1.70,56,1,true),prism);drum.rotation.z=Math.PI/2;drum.scale.z=.25;lens.add(drum);const core=new THREE.Mesh(new THREE.CylinderGeometry(.115,.115,.72,24),new THREE.MeshBasicMaterial({color:0xffc67a,toneMapped:false}));core.rotation.z=Math.PI/2;core.position.z=-.10;lens.add(core);for(const x of [-1.16,1.16]){const p=new THREE.Mesh(new THREE.BoxGeometry(.05,2.18,.07),brassHi);p.position.x=x;machine.add(p)}for(const y of [-1.04,1.04]){const p=new THREE.Mesh(new THREE.BoxGeometry(2.38,.05,.07),brass);p.position.y=y;machine.add(p)}for(let i=0;i<8;i++){const p=new THREE.Mesh(new THREE.BoxGeometry(.032,1.98,.035),brass);p.rotation.z=i*Math.PI/8;machine.add(p)}for(let g=0;g<5;g++){const teeth=20+g*3,gear=new THREE.Group(),rad=.22+g*.07,ring=new THREE.Mesh(new THREE.TorusGeometry(rad,.033,6,teeth),g%2?brass:brassHi);gear.add(ring);for(let i=0;i<teeth;i++){const a=i/teeth*Math.PI*2,t=new THREE.Mesh(new THREE.BoxGeometry(.047,.068,.037),brass);t.position.set(Math.cos(a)*(rad+.038),Math.sin(a)*(rad+.038),0);t.rotation.z=a;gear.add(t)}gear.position.set(1.45+(g%2)*.30,-.60+g*.28,.15);gear.scale.setScalar(.72);gear.userData.speed=(g%2?1:-1)*(.18+g*.035);machine.add(gear)}
const beamGeo=new THREE.ConeGeometry(3.7,30,40,1,true);beamGeo.translate(0,-15,0);beamGeo.rotateZ(-Math.PI/2);const beamMat=new THREE.MeshBasicMaterial({color:0xf1d09a,transparent:true,opacity:.012,depthWrite:false,blending:THREE.AdditiveBlending,side:THREE.DoubleSide,fog:false}),beam=new THREE.Mesh(beamGeo,beamMat);beam.position.set(0,lanternY,0);world.add(beam);
function grassCanvas(seed){const W=1024,H=512,c=cvs(W,H),x=c.getContext('2d'),r=rng(seed);for(let i=0;i<4400;i++){const px=r()*W,base=H*(.84+r()*.16),len=18+r()*96,lean=(r()-.5)*38;x.strokeStyle=`rgba(${39+r()*31},${57+r()*34},${51+r()*23},${.14+r()*.42})`;x.lineWidth=.5+r()*1.7;x.beginPath();x.moveTo(px,base);x.quadraticCurveTo(px+lean*.55,base-len*.52,px+lean,base-len);x.stroke()}return c}function rockCanvas(seed){const W=1024,H=600,c=cvs(W,H),x=c.getContext('2d'),r=rng(seed);x.fillStyle='rgba(8,14,16,.98)';x.beginPath();x.moveTo(0,H);for(let i=0;i<=20;i++)x.lineTo(i/20*W,H*(.60-r()*.20));x.lineTo(W,H);x.closePath();x.fill();return c}function cutMat(c,sway=.04){const m=new THREE.MeshBasicMaterial({map:tx(c),transparent:true,depthWrite:true,alphaTest:.012,side:THREE.DoubleSide,fog:true});m.onBeforeCompile=s=>{s.uniforms.uT=WORLD.uT;s.uniforms.uSway={value:sway};s.vertexShader='uniform float uT;\nuniform float uSway;\n'+s.vertexShader.replace('#include <begin_vertex>','#include <begin_vertex>\nfloat h=uv.y;transformed.x+=sin(uT*.78+position.x*.28)*uSway*h*h;');s.fragmentShader=s.fragmentShader.replace('#include <alphatest_fragment>','float ex=smoothstep(0.,.10,vUv.x)*(1.-smoothstep(.90,1.,vUv.x));float ey=smoothstep(0.,.055,vUv.y);diffuseColor.a*=ex*ey;\n#include <alphatest_fragment>')};return m}[[grassCanvas(11),-5,2.65,-.5,24,11,.028],[rockCanvas(31),-7.2,1.55,1.8,15,8,.003],[grassCanvas(22),4.0,2.65,3.1,14,7,.05],[grassCanvas(33),-2.1,2.7,5.1,11,5.5,.075]].forEach((d,i)=>{const m=new THREE.Mesh(new THREE.PlaneGeometry(d[4],d[5],10,10),cutMat(d[0],d[6]));m.position.set(d[1],d[2],d[3]);m.renderOrder=20+i;m.frustumCulled=false;scene.add(m);WORLD.fg.push(m)});
const sprayGeo=new THREE.PlaneGeometry(.055,.018),sprayMat=new THREE.MeshBasicMaterial({color:0xb8c9c6,transparent:true,opacity:.19,depthWrite:false,side:THREE.DoubleSide}),sprayN=MOBILE?90:180,spray=new THREE.InstancedMesh(sprayGeo,sprayMat,sprayN),dummy=new THREE.Object3D(),sd=[],sr=rng(91);for(let i=0;i<sprayN;i++){const layer=i<sprayN*.3?0:i<sprayN*.75?1:2;sd.push({x:(sr()-.5)*(layer===2?12:28),y:sr()*11-1,z:(sr()-.5)*(layer===2?9:28)+4,sp:.10+sr()*.28,ph:sr()*10,layer})}spray.frustumCulled=false;scene.add(spray);
const desktop=[{p:[13,4.2,23],t:[0,4.3,-1.2],f:39},{p:[7.8,2.9,13.6],t:[0,4.0,-1.2],f:38},{p:[-6.6,2.5,7.8],t:[-3,1.3,-.2],f:45},{p:[1.85,5.0,3.5],t:[0,5.4,-1.2],f:49},{p:[2.8,8.95,2.7],t:[0,lanternY,-1.2],f:45},{p:[-.45,8.85,4.8],t:[0,lanternY,-1.2],f:31},{p:[10,5.6,18],t:[0,4.7,-1.2],f:41}],mobile=[{p:[10,4.0,26],t:[0,4.3,-1.2],f:49},{p:[8.5,3.2,18],t:[0,4.1,-1.2],f:48},{p:[-8,2.5,11],t:[-3,1.2,-.2],f:53},{p:[3.7,5.2,7.2],t:[0,5.1,-1.2],f:56},{p:[3.5,9.0,5.2],t:[0,lanternY,-1.2],f:52},{p:[1.2,9.1,6.4],t:[0,lanternY,-1.2],f:43},{p:[11,5.7,23],t:[0,4.8,-1.2],f:49}],poses=MOBILE?mobile:desktop;
const anchors=[];function measure(){anchors.length=0;sections.forEach(s=>anchors.push(s.offsetTop));anchors.push(document.documentElement.scrollHeight-innerHeight)}measure();function camProg(y){let i=0;for(let k=0;k<sections.length-1;k++)if(y>=anchors[k])i=k;const a=anchors[i]||0,b=anchors[i+1]||a+1;return{i,t:smooth(.05,.95,(y-a)/(b-a))}}const pp=new THREE.Vector3(),pt=new THREE.Vector3(),tmpP=new THREE.Vector3(),tmpT=new THREE.Vector3();let mx=0,my=0;addEventListener('pointermove',e=>{mx=e.clientX/innerWidth-.5;my=e.clientY/innerHeight-.5},{passive:true});
const machineCam=new THREE.PerspectiveCamera(MOBILE?50:42,1,.08,80);machineCam.position.set(MOBILE?2.8:2.15,8.9,MOBILE?4.1:2.2);machineCam.lookAt(0,lanternY,-1.2);const live=$('[data-view="machine"] [data-frame]');function liveRender(){if(!live)return;const r=live.getBoundingClientRect();if(r.bottom<0||r.top>innerHeight||r.width<8||r.height<8)return;const x=Math.max(0,r.left),y=Math.max(0,innerHeight-r.bottom),w=Math.min(innerWidth-x,r.width),h=Math.min(innerHeight-y,r.height);if(w<2||h<2)return;renderer.setScissorTest(true);renderer.setViewport(x,y,w,h);renderer.setScissor(x,y,w,h);machineCam.aspect=w/h;machineCam.updateProjectionMatrix();renderer.render(scene,machineCam);renderer.setScissorTest(false);renderer.setViewport(0,0,innerWidth,innerHeight)}
(function grain(){const S=180,c=cvs(S,S),x=c.getContext('2d'),im=x.createImageData(S,S),d=im.data,r=rng(9);for(let i=0;i<S*S;i++){const v=105+r()*95;d[i*4]=d[i*4+1]=d[i*4+2]=v;d[i*4+3]=255}x.putImageData(im,0,0);if($('#grain'))$('#grain').style.backgroundImage=`url(${c.toDataURL('image/png')})`})();
const clock=new THREE.Clock();let sy=scrollY;function tick(){requestAnimationFrame(tick);const dt=Math.min(clock.getDelta(),.033),time=clock.elapsedTime;WORLD.uT.value=time;sy=lerp(sy,scrollY,REDUCE?1:.09);const pr=camProg(sy),a=poses[pr.i],b=poses[Math.min(pr.i+1,poses.length-1)];pp.set(...a.p).lerp(tmpP.set(...b.p),pr.t);pt.set(...a.t).lerp(tmpT.set(...b.t),pr.t);camera.position.lerp(pp,.13);if(!MOBILE){camera.position.x+=mx*.07;camera.position.y-=my*.035}camera.fov=lerp(a.f,b.f,pr.t);camera.updateProjectionMatrix();camera.lookAt(pt);const sec=pr.i;renderer.toneMappingExposure=lerp(renderer.toneMappingExposure,sec===4?1.00:sec===2?.73:sec===5?.91:.81,.05);scene.fog.density=lerp(scene.fog.density,sec===4?.009:sec===5?.024:sec===3?.020:.015,.045);hemi.intensity=lerp(hemi.intensity,sec===4?.14:sec===2?.20:.28,.05);moon.intensity=lerp(moon.intensity,sec===4?.48:sec===2?.38:1.0,.05);houseLight.intensity=lerp(houseLight.intensity,sec===2?3.4:.5,.05);opticWarm.intensity=lerp(opticWarm.intensity,sec===4?6.2:sec===5?4.8:.6,.055);opticRim.intensity=lerp(opticRim.intensity,sec===4?6.5:sec===5?3.0:.35,.055);beamMat.opacity=lerp(beamMat.opacity,sec===5?.12:sec===4?.028:.006,.06);skyMat.uniforms.uDawn.value=lerp(skyMat.uniforms.uDawn.value,sec===6?1:0,.025);seaMat.uniforms.uDawn.value=skyMat.uniforms.uDawn.value;beam.rotation.y=time*.12+sy*.0015;machine.children.forEach(o=>{if(o.userData.speed)o.rotation.z+=o.userData.speed*dt});const ms=$('#machine'),mr=ms?.getBoundingClientRect(),mt=mr?clamp(-mr.top/Math.max(1,ms.offsetHeight-innerHeight),0,1):0;if($('#azimuthBar'))$('#azimuthBar').style.width=`${mt*100}%`;beam.rotation.y+=mt*Math.PI*2.1;sd.forEach((d,i)=>{d.x+=d.sp*dt*(d.layer===2?1.6:1);d.y+=Math.sin(time*.7+d.ph)*dt*.035;if(d.x>18)d.x=-18;dummy.position.set(d.x,d.y,d.z);dummy.rotation.set(time*(.2+d.sp)+d.ph,time*(.16+d.sp*.4),time*(.28+d.sp*.5));const s=d.layer===2?1.5:d.layer===1?1:.62;dummy.scale.setScalar(s);dummy.updateMatrix();spray.setMatrixAt(i,dummy.matrix)});spray.instanceMatrix.needsUpdate=true;renderer.setScissorTest(false);renderer.setViewport(0,0,innerWidth,innerHeight);renderer.render(scene,camera);liveRender();window.__FARO_QA__.ready=true}tick();function resize(){renderer.setSize(innerWidth,innerHeight,false);renderer.setPixelRatio(Math.min(devicePixelRatio,innerWidth<700?1.15:1.45));camera.aspect=innerWidth/innerHeight;camera.updateProjectionMatrix();measure()}addEventListener('resize',resize,{passive:true});resize();
})();