(()=>{
const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
const clamp=(v,a,b)=>Math.max(a,Math.min(b,v)),lerp=(a,b,t)=>a+(b-a)*t,smooth=(a,b,t)=>{t=clamp((t-a)/(b-a),0,1);return t*t*(3-2*t)};
const REDUCE=matchMedia('(prefers-reduced-motion:reduce)').matches,COARSE=matchMedia('(pointer:coarse)').matches;
const nav=$('#nav'),burger=$('#burger'),sections=$$('.sec'),links=$$('.nav-links a');

// Kage-style editorial reveal, navigation and rail.
const io=new IntersectionObserver(es=>es.forEach(e=>e.isIntersecting&&e.target.classList.add('rv-in')),{threshold:.14,rootMargin:'0px 0px -7%'});$$('[data-rv]').forEach(el=>io.observe(el));
burger.addEventListener('click',()=>{const o=document.body.classList.toggle('nav-open');burger.setAttribute('aria-expanded',String(o))});
links.forEach(a=>a.addEventListener('click',()=>document.body.classList.remove('nav-open')));
sections.forEach((s,i)=>{const b=document.createElement('button');b.innerHTML='<i></i>';b.title=s.id;b.addEventListener('click',()=>scrollTo({top:s.offsetTop-24,behavior:REDUCE?'auto':'smooth'}));$('#rail').appendChild(b)});
const dots=$$('#rail button');let active=0,lastY=0;
function sectionState(){const mid=innerHeight*.47;let best=0,bd=1e9;sections.forEach((s,i)=>{const r=s.getBoundingClientRect(),d=Math.abs(r.top+r.height*.44-mid);if(d<bd){bd=d;best=i}});active=best;dots.forEach((d,i)=>d.classList.toggle('on',i===active));links.forEach(a=>a.classList.toggle('on',a.hash==='#'+sections[active].id));nav.classList.toggle('stuck',scrollY>40);lastY=scrollY}
addEventListener('scroll',sectionState,{passive:true});sectionState();

// Section foregrounds are lifted outside .page while active, exactly the stacking-context strategy used by Kage.
function wireForegroundStages(){const pairs=$$('.sec .fg').map(stage=>({section:stage.closest('.sec'),stage}));const sky=$('#fg-sky'),ratios=new Map(pairs.map(p=>[p.section,0])),homes=new WeakMap(pairs.map(p=>[p.stage,p.section])),timers=new WeakMap();let current=null;
 const lift=stage=>{if(stage.parentNode===sky)return;sky.appendChild(stage);void stage.offsetWidth};
 const park=stage=>{const home=homes.get(stage);if(home&&stage.parentNode!==home)home.insertBefore(stage,home.firstChild)};
 const retire=stage=>{if(!stage||stage===current)return;clearTimeout(timers.get(stage));stage.classList.remove('fg-active');stage.classList.add('fg-retiring');if(REDUCE){stage.classList.remove('fg-retiring');park(stage);return}timers.set(stage,setTimeout(()=>{stage.classList.remove('fg-retiring');park(stage)},900))};
 const activate=stage=>{if(!stage||stage===current)return;clearTimeout(timers.get(stage));stage.classList.remove('fg-retiring');lift(stage);stage.classList.add('fg-active');const old=current;current=stage;retire(old)};
 const ob=new IntersectionObserver(es=>{es.forEach(e=>ratios.set(e.target,e.isIntersecting?e.intersectionRatio:0));let next=pairs[0];pairs.forEach(p=>{if((ratios.get(p.section)||0)>(ratios.get(next.section)||0))next=p});if((ratios.get(next.section)||0)>0)activate(next.stage)},{rootMargin:'-12% 0px -12%',threshold:[0,.12,.32,.55]});pairs.forEach(p=>ob.observe(p.section));}
wireForegroundStages();

// Cursor is an instrument, not a flourish.
const cursor=$('#cursor');if(!COARSE&&matchMedia('(hover:hover)').matches){let x=innerWidth/2,y=innerHeight/2,tx=x,ty=y;addEventListener('pointermove',e=>{tx=e.clientX;ty=e.clientY},{passive:true});(function follow(){x=lerp(x,tx,.18);y=lerp(y,ty,.18);cursor.style.transform=`translate3d(${x}px,${y}px,0)`;requestAnimationFrame(follow)})()}

if(!window.THREE){document.body.classList.add('no-webgl');return}
const renderer=new THREE.WebGLRenderer({canvas:$('#gl'),antialias:true,alpha:false,powerPreference:'high-performance'});renderer.setPixelRatio(Math.min(devicePixelRatio,1.7));renderer.setSize(innerWidth,innerHeight,false);renderer.outputEncoding=THREE.sRGBEncoding;renderer.toneMapping=THREE.ACESFilmicToneMapping;renderer.toneMappingExposure=.95;renderer.shadowMap.enabled=true;renderer.shadowMap.type=THREE.PCFSoftShadowMap;
const scene=new THREE.Scene();scene.background=new THREE.Color(0x05090c);scene.fog=new THREE.FogExp2(0x0a151b,.018);
const camera=new THREE.PerspectiveCamera(41,innerWidth/innerHeight,.08,240);
const WORLD={uT:{value:0},fg:[],spray:[],machine:new THREE.Group()};

function cvs(w,h){const c=document.createElement('canvas');c.width=w;c.height=h;return c}
function texture(c,repeat=[1,1]){const t=new THREE.CanvasTexture(c);t.wrapS=t.wrapT=THREE.RepeatWrapping;t.repeat.set(...repeat);t.encoding=THREE.sRGBEncoding;t.anisotropy=8;return t}
function stoneTexture(seed=1){const S=512,c=cvs(S,S),x=c.getContext('2d');x.fillStyle='#aeb4af';x.fillRect(0,0,S,S);let r=seed*9973;const rnd=()=>((r=Math.imul(r^r>>>15,1|r))>>>0)/4294967295;for(let i=0;i<9000;i++){const v=145+rnd()*92;x.fillStyle=`rgba(${v},${v+3},${v+1},${.02+rnd()*.13})`;const q=.5+rnd()*2.5;x.fillRect(rnd()*S,rnd()*S,q,q)}for(let i=0;i<45;i++){x.strokeStyle=`rgba(63,72,69,${.035+rnd()*.08})`;x.lineWidth=.5+rnd()*1.8;x.beginPath();let y=rnd()*S;x.moveTo(0,y);for(let k=1;k<9;k++){y+=(rnd()-.5)*15;x.lineTo(k*S/8,y)}x.stroke()}for(let i=0;i<220;i++){x.fillStyle=`rgba(238,242,236,${rnd()*.07})`;x.beginPath();x.arc(rnd()*S,rnd()*S,1+rnd()*4,0,Math.PI*2);x.fill()}return texture(c,[2.2,2.2])}
function rustTexture(seed=3){const S=512,c=cvs(S,S),x=c.getContext('2d');const g=x.createLinearGradient(0,0,S,S);g.addColorStop(0,'#1a2021');g.addColorStop(.5,'#302820');g.addColorStop(1,'#121819');x.fillStyle=g;x.fillRect(0,0,S,S);let r=seed*9187;const rnd=()=>((r=Math.imul(r^r>>>14,1|r))>>>0)/4294967295;for(let i=0;i<2300;i++){x.fillStyle=`rgba(${105+rnd()*90},${48+rnd()*52},${24+rnd()*34},${rnd()*.2})`;x.beginPath();x.arc(rnd()*S,rnd()*S,.5+rnd()*5,0,Math.PI*2);x.fill()}for(let i=0;i<130;i++){x.strokeStyle=`rgba(225,232,225,${rnd()*.07})`;x.beginPath();x.moveTo(rnd()*S,rnd()*S);x.lineTo(rnd()*S,rnd()*S);x.stroke()}return texture(c,[2,2])}
function rockTexture(seed=7){const S=512,c=cvs(S,S),x=c.getContext('2d');x.fillStyle='#101719';x.fillRect(0,0,S,S);let r=seed*12347;const rnd=()=>((r=Math.imul(r^r>>>13,1|r))>>>0)/4294967295;for(let i=0;i<4500;i++){const v=18+rnd()*54;x.fillStyle=`rgba(${v},${v+7},${v+8},${rnd()*.18})`;x.fillRect(rnd()*S,rnd()*S,1+rnd()*7,1+rnd()*3)}return texture(c,[2.4,2.4])}
const stone=new THREE.MeshStandardMaterial({map:stoneTexture(),color:0xc5cbc5,roughness:.9,metalness:0});const iron=new THREE.MeshStandardMaterial({map:rustTexture(),color:0x363431,roughness:.58,metalness:.7});const ironDark=new THREE.MeshStandardMaterial({map:rustTexture(9),color:0x151b1c,roughness:.5,metalness:.76});const rockMat=new THREE.MeshStandardMaterial({map:rockTexture(),color:0x1a2427,roughness:.9,metalness:.03});const brass=new THREE.MeshStandardMaterial({color:0x9a713d,roughness:.31,metalness:.92});const glass=new THREE.MeshPhysicalMaterial({color:0xb9d3ce,transparent:true,opacity:.32,transmission:.72,thickness:.7,ior:1.46,roughness:.035,metalness:0});

// Sky/sea share one palette; no photographic plate sits over them.
const skyGeo=new THREE.SphereGeometry(150,32,20);const skyMat=new THREE.ShaderMaterial({side:THREE.BackSide,depthWrite:false,uniforms:{uDawn:{value:0}},vertexShader:`varying vec3 vP;void main(){vP=position;gl_Position=projectionMatrix*modelViewMatrix*vec4(position,1.);}`,fragmentShader:`uniform float uDawn;varying vec3 vP;void main(){float h=clamp(normalize(vP).y*.5+.5,0.,1.);vec3 n1=vec3(.018,.035,.052),n2=vec3(.075,.12,.14);vec3 d1=vec3(.23,.31,.33),d2=vec3(.72,.61,.48);vec3 c=mix(n1,n2,h);vec3 dawn=mix(d1,d2,h);gl_FragColor=vec4(mix(c,dawn,uDawn),1.);}`});scene.add(new THREE.Mesh(skyGeo,skyMat));
const seaGeo=new THREE.PlaneGeometry(190,190,128,128);const seaMat=new THREE.ShaderMaterial({uniforms:{uTime:WORLD.uT,uDawn:{value:0}},vertexShader:`uniform float uTime;varying float vH;varying vec2 vUv2;void main(){vec3 p=position;float a=sin(p.x*.27+uTime*.31)*.19+sin(p.y*.17-uTime*.23)*.14+sin((p.x+p.y)*.09+uTime*.14)*.12+sin(p.x*.72-p.y*.39+uTime*.49)*.035;p.z+=a;vH=a;vUv2=uv;gl_Position=projectionMatrix*modelViewMatrix*vec4(p,1.);}`,fragmentShader:`uniform float uDawn;varying float vH;varying vec2 vUv2;void main(){vec3 deep=vec3(.012,.038,.052),lift=vec3(.075,.15,.17);float crest=smoothstep(.10,.40,vH);vec3 c=mix(deep,lift,crest*.44);c+=vec3(.16,.18,.17)*pow(max(vH,0.),4.)*.8;vec3 dawn=mix(vec3(.10,.18,.20),vec3(.28,.32,.30),crest);gl_FragColor=vec4(mix(c,dawn,uDawn),1.);}`});const sea=new THREE.Mesh(seaGeo,seaMat);sea.rotation.x=-Math.PI/2;sea.position.y=-2.85;scene.add(sea);

// Lighting tokens by chapter.
const hemi=new THREE.HemisphereLight(0x7893a0,0x061013,.54);scene.add(hemi);const moon=new THREE.DirectionalLight(0xa5c0ca,1.65);moon.position.set(-14,18,10);moon.castShadow=true;moon.shadow.mapSize.set(1024,1024);scene.add(moon);const practical=new THREE.PointLight(0xe6a05b,3.2,26,2);practical.position.set(-3.2,2.1,1.7);scene.add(practical);const lanternLight=new THREE.PointLight(0xf1bd72,5.5,30,2);lanternLight.position.set(0,9.3,-1.2);scene.add(lanternLight);const machineSpot=new THREE.SpotLight(0xb9d1d1,2.5,30,Math.PI/6,.55,1.4);machineSpot.position.set(6,12,7);machineSpot.target.position.set(0,8.8,-1.2);scene.add(machineSpot,machineSpot.target);

// Terrain is a set, not one primitive.
const cliff=new THREE.Group();for(let i=0;i<13;i++){const geo=new THREE.IcosahedronGeometry(2.5+Math.random()*4.4,2),p=geo.attributes.position;for(let j=0;j<p.count;j++){const x=p.getX(j),y=p.getY(j),z=p.getZ(j),n=1+Math.sin(x*2.1+z*1.7+i)*.08+Math.sin(y*3.2+i)*.05;p.setXYZ(j,x*n,y*n*.68,z*n)}geo.computeVertexNormals();const m=new THREE.Mesh(geo,rockMat);m.position.set((Math.random()-.5)*14,-2.1+Math.random()*1.4,(Math.random()-.5)*10-1);m.scale.set(1+Math.random()*1.7,.55+Math.random()*.5,.8+Math.random());m.rotation.y=Math.random()*Math.PI;m.castShadow=m.receiveShadow=true;cliff.add(m)}scene.add(cliff);

// Lighthouse kit — one spatial source for the hero object.
const world=new THREE.Group();world.position.z=-1.2;scene.add(world);const tower=new THREE.Group();world.add(tower);
for(let i=0;i<7;i++){const h=1.25,y=.15+i*1.22,r=1.72-i*.055;const seg=new THREE.Mesh(new THREE.CylinderGeometry(r-.05,r,h,56,3),stone);seg.position.y=y+2.5;seg.rotation.y=(i%2?1:-1)*.018;seg.castShadow=seg.receiveShadow=true;tower.add(seg);const seam=new THREE.Mesh(new THREE.TorusGeometry(r,.018,5,56),new THREE.MeshStandardMaterial({color:0x727a74,roughness:.95}));seam.rotation.x=Math.PI/2;seam.position.y=seg.position.y-h*.5;tower.add(seam)}
for(let i=0;i<5;i++){const a=.55+i*.83,y=2.2+i*1.25;const aperture=new THREE.Mesh(new THREE.BoxGeometry(.46,.72,.08),new THREE.MeshStandardMaterial({color:0x071012,roughness:.28,metalness:.12}));aperture.position.set(Math.sin(a)*1.5,y,Math.cos(a)*1.5);aperture.lookAt(0,y,0);tower.add(aperture);const sill=new THREE.Mesh(new THREE.BoxGeometry(.64,.08,.22),stone);sill.position.copy(aperture.position);sill.position.y-=.42;sill.lookAt(0,sill.position.y,0);tower.add(sill)}
const house=new THREE.Group();const hb=new THREE.Mesh(new THREE.BoxGeometry(6.3,2.45,4.5),stone);hb.position.set(-3.45,.2,.35);hb.castShadow=hb.receiveShadow=true;house.add(hb);const roof=new THREE.Mesh(new THREE.CylinderGeometry(4.1,4.1,.32,4),ironDark);roof.rotation.y=Math.PI/4;roof.scale.z=.72;roof.position.set(-3.45,1.55,.35);house.add(roof);for(let i=0;i<3;i++){const w=new THREE.Mesh(new THREE.BoxGeometry(.72,.88,.08),new THREE.MeshStandardMaterial({color:i===1?0xb7783f:0x081012,emissive:i===1?0x6e3512:0,emissiveIntensity:i===1?.9:0,roughness:.24}));w.position.set(-5+i*1.55,.22,2.63);house.add(w)}world.add(house);
const gallery=new THREE.Mesh(new THREE.CylinderGeometry(2.05,2.05,.2,56),iron);gallery.position.y=8.25;tower.add(gallery);for(let i=0;i<36;i++){const a=i/36*Math.PI*2,p=new THREE.Mesh(new THREE.CylinderGeometry(.021,.021,.82,6),ironDark);p.position.set(Math.cos(a)*1.92,8.66,Math.sin(a)*1.92);tower.add(p)}for(const y of [8.53,8.87]){const ring=new THREE.Mesh(new THREE.TorusGeometry(1.92,.023,6,72),ironDark);ring.rotation.x=Math.PI/2;ring.position.y=y;tower.add(ring)}
const lantern=new THREE.Group();const room=new THREE.Mesh(new THREE.CylinderGeometry(1.48,1.48,1.75,28,1,true),glass);room.position.y=9.22;lantern.add(room);for(let i=0;i<14;i++){const a=i/14*Math.PI*2,p=new THREE.Mesh(new THREE.BoxGeometry(.035,1.76,.05),ironDark);p.position.set(Math.cos(a)*1.49,9.22,Math.sin(a)*1.49);p.rotation.y=-a;lantern.add(p)}const cap=new THREE.Mesh(new THREE.ConeGeometry(1.7,1.0,36),ironDark);cap.position.y=10.58;lantern.add(cap);tower.add(lantern);

// Stair: visible geometry for the ascent instead of a photographic transition.
const stair=new THREE.Group();for(let i=0;i<54;i++){const a=i*.32,y=1.25+i*.13,r=1.05;const step=new THREE.Mesh(new THREE.BoxGeometry(1.18,.055,.34),ironDark);step.position.set(Math.cos(a)*r,y,Math.sin(a)*r);step.rotation.y=-a+.18;stair.add(step);if(i%2===0){const post=new THREE.Mesh(new THREE.CylinderGeometry(.018,.018,.62,6),iron);post.position.set(Math.cos(a)*1.5,y+.3,Math.sin(a)*1.5);stair.add(post)}}tower.add(stair);

// Fresnel and machine: hero 3D, no duplicate plate.
const machine=WORLD.machine;machine.position.y=9.15;tower.add(machine);const lensGroup=new THREE.Group();machine.add(lensGroup);for(let i=0;i<13;i++){const r=.24+i*.085;const tor=new THREE.Mesh(new THREE.TorusGeometry(r,.024,8,72),glass);tor.rotation.x=Math.PI/2;tor.position.z=(i-6)*.012;lensGroup.add(tor)}for(let i=0;i<8;i++){const bar=new THREE.Mesh(new THREE.BoxGeometry(.035,1.95,.045),brass);bar.rotation.z=i*Math.PI/8;machine.add(bar)}const core=new THREE.Mesh(new THREE.CylinderGeometry(.16,.16,.82,20),new THREE.MeshBasicMaterial({color:0xffcf88,toneMapped:false}));core.rotation.z=Math.PI/2;machine.add(core);for(let g=0;g<5;g++){const teeth=22+g*4,gear=new THREE.Group(),rr=.28+g*.11;const ring=new THREE.Mesh(new THREE.TorusGeometry(rr,.045,6,teeth),brass);gear.add(ring);for(let i=0;i<teeth;i++){const t=new THREE.Mesh(new THREE.BoxGeometry(.06,.09,.05),brass),a=i/teeth*Math.PI*2;t.position.set(Math.cos(a)*(rr+.055),Math.sin(a)*(rr+.055),0);t.rotation.z=a;gear.add(t)}gear.position.set(-.9+g*.43,-.55+(g%2)*.28,.28);gear.scale.setScalar(.65);machine.add(gear);gear.userData.speed=(g%2?1:-1)*(.18+g*.04)}
const beamGeo=new THREE.ConeGeometry(3.8,30,40,1,true);beamGeo.translate(0,-15,0);beamGeo.rotateZ(-Math.PI/2);const beamMat=new THREE.MeshBasicMaterial({color:0xf2d39c,transparent:true,opacity:.03,depthWrite:false,blending:THREE.AdditiveBlending,side:THREE.DoubleSide,fog:false});const beam=new THREE.Mesh(beamGeo,beamMat);beam.position.set(0,9.15,0);tower.add(beam);

// Kage-style procedural alpha cutouts INSIDE Three: true depth + alphaTest + feather.
function grassCutout(seed=1){const W=1024,H=512,c=cvs(W,H),x=c.getContext('2d');x.clearRect(0,0,W,H);let r=seed*7349;const rnd=()=>((r=Math.imul(r^r>>>15,1|r))>>>0)/4294967295;for(let i=0;i<7000;i++){const px=rnd()*W,base=H*(.8+rnd()*.22),len=25+rnd()*120,lean=(rnd()-.5)*50;x.strokeStyle=`rgba(${55+rnd()*45},${72+rnd()*50},${62+rnd()*35},${.16+rnd()*.55})`;x.lineWidth=.45+rnd()*1.7;x.beginPath();x.moveTo(px,base);x.quadraticCurveTo(px+lean*.55,base-len*.55,px+lean,base-len);x.stroke()}return c}
function rockCutout(seed=4){const W=1024,H=600,c=cvs(W,H),x=c.getContext('2d');x.clearRect(0,0,W,H);let r=seed*4129;const rnd=()=>((r=Math.imul(r^r>>>14,1|r))>>>0)/4294967295;x.fillStyle='#11191b';for(let i=0;i<8;i++){x.beginPath();const cx=W*(.08+i*.12),cy=H*(.78-rnd()*.12),rx=100+rnd()*150,ry=70+rnd()*110;x.ellipse(cx,cy,rx,ry,-.15+rnd()*.3,0,Math.PI*2);x.fill()}return c}
function cutoutMaterial(canvas,sway=.05){const mat=new THREE.MeshBasicMaterial({map:texture(canvas),transparent:true,depthWrite:true,alphaTest:.012,side:THREE.DoubleSide,fog:true});mat.onBeforeCompile=sh=>{sh.uniforms.uT=WORLD.uT;sh.uniforms.uSway={value:sway};sh.vertexShader='uniform float uT;uniform float uSway;\n'+sh.vertexShader.replace('#include <begin_vertex>','#include <begin_vertex>\nfloat h=uv.y;transformed.x+=sin(uT*.85+position.x*.3)*uSway*h*h;transformed.y+=cos(uT*.62+position.x*.5)*uSway*.3*h*h;');sh.fragmentShader=sh.fragmentShader.replace('#include <alphatest_fragment>','float feX=smoothstep(0.0,.10,vUv.x)*(1.0-smoothstep(.90,1.0,vUv.x));float feY=smoothstep(0.0,.07,vUv.y);diffuseColor.a*=feX*feY;\n#include <alphatest_fragment>')};return mat}
function buildForeground(){const layers=[['grassFar',grassCutout(11),-5,2.7,-.4,24,12,.035],['rockLeft',rockCutout(31),-7.5,1.8,1.7,16,9,.004],['grassMid',grassCutout(22),4,2.75,3.4,15,7.5,.06],['grassNear',grassCutout(33),-2,2.8,5.5,12,6,.09],['rockNear',rockCutout(47),-6.7,1.3,6.2,9,5.5,.006]];layers.forEach(L=>{const m=new THREE.Mesh(new THREE.PlaneGeometry(L[5],L[6],10,10),cutoutMaterial(L[1],L[7]));m.position.set(L[2],L[3],L[4]);m.renderOrder=20+WORLD.fg.length;m.frustumCulled=false;scene.add(m);WORLD.fg.push(m)})}buildForeground();

// Salt spray adapts Kage's layered leaf logic: far/mid/near, tumble, recycle ahead of camera.
const sprayGeo=new THREE.PlaneGeometry(.08,.028),sprayMat=new THREE.MeshBasicMaterial({color:0xbfd0cc,transparent:true,opacity:.26,depthWrite:false,side:THREE.DoubleSide});const sprayCount=280,spray=new THREE.InstancedMesh(sprayGeo,sprayMat,sprayCount),dummy=new THREE.Object3D();const sprayData=[];for(let i=0;i<sprayCount;i++){const layer=i<90?0:i<210?1:2;const d={x:(Math.random()-.5)*(layer===2?13:28),y:Math.random()*12-1,z:(Math.random()-.5)*(layer===2?10:30)+4,sp:.12+Math.random()*.36,phase:Math.random()*10,layer};sprayData.push(d)}spray.frustumCulled=false;scene.add(spray);

// Camera states: same world, authored shots. Interpolate continuously as Kage does.
const poses=[
 {p:[13.8,4.8,24],t:[0,4.5,-1],f:40},{p:[8.2,3.1,14.2],t:[0,4.3,-1],f:39},{p:[-7.0,2.7,8.2],t:[-3.2,1.4,.5],f:47},{p:[2.1,5.7,3.9],t:[0,5.9,-1.2],f:52},{p:[2.8,9.35,5.0],t:[0,9.15,-1.2],f:58},{p:[-.7,9.3,5.6],t:[0,9.15,-1.2],f:34},{p:[10.8,6.0,19],t:[0,5.0,-1.2],f:43}
];
const anchors=[];function measure(){anchors.length=0;sections.forEach(s=>anchors.push(s.offsetTop));anchors.push(document.documentElement.scrollHeight-innerHeight)}measure();addEventListener('resize',measure,{passive:true});
function cameraProgress(y){let i=0;for(let k=0;k<sections.length-1;k++){if(y>=anchors[k])i=k}const a=anchors[i]||0,b=anchors[i+1]||a+1;return {i,t:smooth(.05,.95,(y-a)/(b-a))}}
const cp=new THREE.Vector3(),ct=new THREE.Vector3(),pp=new THREE.Vector3(),pt=new THREE.Vector3();let mx=0,my=0;addEventListener('pointermove',e=>{mx=e.clientX/innerWidth-.5;my=e.clientY/innerHeight-.5},{passive:true});

// One live window gets another camera into the SAME sanctuary/world, not a second image.
const machineCam=new THREE.PerspectiveCamera(58,1,.08,120);machineCam.position.set(1.7,9.05,2.1);machineCam.lookAt(0,9.15,-1.2);const live=$('[data-view="machine"] [data-frame]');
function renderLive(){if(!live)return;const r=live.getBoundingClientRect();if(r.bottom<0||r.top>innerHeight||r.width<8||r.height<8)return;const x=Math.max(0,r.left),y=Math.max(0,innerHeight-r.bottom),w=Math.min(innerWidth-x,r.width),h=Math.min(innerHeight-y,r.height);if(w<=0||h<=0)return;renderer.setScissorTest(true);renderer.setViewport(x,y,w,h);renderer.setScissor(x,y,w,h);machineCam.aspect=w/h;machineCam.updateProjectionMatrix();renderer.render(scene,machineCam);renderer.setScissorTest(false);renderer.setViewport(0,0,innerWidth,innerHeight)}

// Grain made at runtime like Kage; no remote texture needed.
(function grain(){const S=180,c=cvs(S,S),x=c.getContext('2d'),im=x.createImageData(S,S),d=im.data;for(let i=0;i<S*S;i++){const v=105+Math.random()*100;d[i*4]=d[i*4+1]=d[i*4+2]=v;d[i*4+3]=255}x.putImageData(im,0,0);$('#grain').style.backgroundImage=`url(${c.toDataURL('image/png')})`})();

const clock=new THREE.Clock();let smoothScroll=scrollY;
function tick(){requestAnimationFrame(tick);const dt=Math.min(clock.getDelta(),.033),time=clock.elapsedTime;WORLD.uT.value=time;smoothScroll=lerp(smoothScroll,scrollY,REDUCE?1:.075);const pr=cameraProgress(smoothScroll),a=poses[pr.i],b=poses[Math.min(pr.i+1,poses.length-1)];pp.set(...a.p).lerp(cp.set(...b.p),pr.t);pt.set(...a.t).lerp(ct.set(...b.t),pr.t);camera.position.lerp(pp,.11);camera.position.x+=mx*.10;camera.position.y+=-my*.05;camera.fov=lerp(a.f,b.f,pr.t);camera.updateProjectionMatrix();camera.lookAt(pt);
 const sec=pr.i,local=pr.t;renderer.toneMappingExposure=lerp(renderer.toneMappingExposure,sec===4?1.18:sec===5?1.05:sec===6?1.02:.92,.04);scene.fog.density=lerp(scene.fog.density,sec===5?.028:sec===3?.022:.017,.035);hemi.intensity=lerp(hemi.intensity,sec===2?.35:sec===4?.62:.54,.04);moon.intensity=lerp(moon.intensity,sec===2?.55:sec===4?1.35:1.65,.04);practical.intensity=lerp(practical.intensity,sec===2?4.0:.8,.05);lanternLight.intensity=lerp(lanternLight.intensity,sec===4||sec===5?6.2:2.2,.05);machineSpot.intensity=lerp(machineSpot.intensity,sec===4?3.4:.8,.05);beamMat.opacity=lerp(beamMat.opacity,sec===5?.14:sec===4?.055:.018,.055);skyMat.uniforms.uDawn.value=lerp(skyMat.uniforms.uDawn.value,sec===6?1:0,.025);seaMat.uniforms.uDawn.value=skyMat.uniforms.uDawn.value;
 beam.rotation.y=time*.13+smoothScroll*.0018;lensGroup.rotation.y=-beam.rotation.y*.25;WORLD.machine.children.forEach(o=>{if(o.userData.speed)o.rotation.z+=o.userData.speed*dt});
 // The machine sticky scroll drives azimuth rather than opacity.
 const machineSec=$('#machine'),mr=machineSec.getBoundingClientRect(),mt=clamp(-mr.top/Math.max(1,machineSec.offsetHeight-innerHeight),0,1);$('#azimuthBar').style.width=`${mt*100}%`;beam.rotation.y+=mt*Math.PI*2.2;
 // Tumble/recycle spray by depth layer.
 sprayData.forEach((d,i)=>{d.x+=d.sp*dt*(d.layer===2?1.8:1);d.y+=Math.sin(time*.7+d.phase)*dt*.045;if(d.x>18)d.x=-18;dummy.position.set(d.x,d.y,d.z);dummy.rotation.set(time*(.25+d.sp)+d.phase,time*(.18+d.sp*.4),time*(.3+d.sp*.5));const s=d.layer===2?1.7:d.layer===1?1:.65;dummy.scale.setScalar(s);dummy.updateMatrix();spray.setMatrixAt(i,dummy.matrix)});spray.instanceMatrix.needsUpdate=true;
 renderer.setScissorTest(false);renderer.setViewport(0,0,innerWidth,innerHeight);renderer.render(scene,camera);renderLive();}
tick();
function resize(){renderer.setSize(innerWidth,innerHeight,false);renderer.setPixelRatio(Math.min(devicePixelRatio,1.7));camera.aspect=innerWidth/innerHeight;camera.updateProjectionMatrix();measure()}addEventListener('resize',resize,{passive:true});resize();
})();