(()=>{
const copy={
 en:{
  weather:{k:'WEATHER INSIDE',h:'How is the weather inside?',i:'No diagnosis. No score. Just a way to name the weather you are carrying right now.',opts:[['calm','Calm'],['fog','Fog'],['heavy','Heavy sea'],['storm','Storm']],res:{calm:'Calm is allowed to be noticed too. You do not have to wait for a storm to check in with yourself.',fog:'Fog can make the next direction hard to see. You do not need the whole route; only the next visible marker.',heavy:'A heavy sea asks for less speed and more support. You can choose one small next step below.',storm:'If it feels like a storm, do not navigate it alone. You can still choose one small next step — or go directly to Another Station.'}},
  step:{k:'ONE STEP',h:'Not the whole journey. Only the next one.',i:'Choose one action small enough to be possible now.',opts:[['tell','Tell one person'],['company','Ask someone to stay with me'],['write','Write one sentence about what I need'],['support','Contact a support service']],res:{tell:'Your next step can be one sentence: “I am having a hard time and I need to talk.”',company:'You can ask without explaining everything: “Could you stay with me for a while? I do not want to be alone right now.”',write:'You do not need perfect words. Write only what another person would need to know to come closer.',support:'You can use Another Station at the end of this journey, or go there now.'}},
  signal:{k:'SEND A SIGNAL',h:'You do not have to tell the whole story.',i:'Choose the first sentence. Faro will not send or store it. You can copy it or use your device share sheet.',opts:[['listen','I need someone to listen.'],['alone','I do not want to be alone right now.'],['hard','I am struggling and I could use some company.']],templates:{listen:'I am not doing very well lately. I do not need you to fix it. Could you listen for a while?',alone:'I am having a difficult time and I do not want to be alone right now. Could you stay with me or call me?',hard:'Things feel heavy right now. I am not sure what I need yet, but I could really use some company.'},copy:'Copy signal',share:'Share signal',copied:'Signal copied',ready:'Your signal is ready to leave the lighthouse.'},
  answer:{k:'ANOTHER LIGHT ANSWERS',h:'A signal creates the possibility of connection.',i:'The second light is symbolic — it is not a real reply from another person. It appears to mark the moment you make your position easier to see.',note:'A second light is now visible on the horizon. <b>Not because everything is solved, but because a signal can be answered.</b>'},
  station:{k:'ANOTHER STATION',h:'You do not have to navigate alone.',i:'Real human and professional support in Spain. Choose the station that fits what you need.',cards:[
   ['LISTENING','Teléfono de la Esperanza','Urgent, free, anonymous emotional support and active listening.','Call 717 003 717','tel:717003717','Official site','https://telefonodelaesperanza.org/intervencion-en-crisis'],
   ['ALICANTE','Teléfono de la Esperanza · Alicante','Local 24h contact published by the Alicante centre.','Call 965 131 122','tel:965131122','Alicante centre','https://telefonodelaesperanza.org/alicante'],
   ['ADDICTIONS + MENTAL HEALTH','Proyecto Hombre','Integrated, person-centred support for addictions and mental health. Alicante centre: 965 112 125.','Call Alicante','tel:965112125','Find a centre','https://proyectohombre.es/contacta/'],
   ['SUICIDAL THOUGHTS / RISK','Línea 024','National, free, confidential, 24/7 support for people with suicidal thoughts or risk, and their families.','Call 024','tel:024','Official 024','https://www.sanidad.gob.es/linea024/'],
   ['IMMEDIATE EMERGENCY','112','If there is an immediate life-threatening emergency, call emergency services now.','Call 112','tel:112','', '']
  ],d:'Faro is a storytelling and support-navigation experience. It does not diagnose, assess clinical risk, provide therapy or replace professional care.'}
 },
 es:{
  weather:{k:'EL TIEMPO POR DENTRO',h:'¿Qué tiempo hace por dentro?',i:'Sin diagnóstico. Sin puntuación. Sólo una forma de nombrar el tiempo que llevas contigo ahora mismo.',opts:[['calm','Calma'],['fog','Niebla'],['heavy','Mar gruesa'],['storm','Tormenta']],res:{calm:'También merece la pena notar la calma. No necesitas esperar a una tormenta para preguntarte cómo estás.',fog:'La niebla puede dificultar ver la dirección siguiente. No necesitas conocer toda la ruta; sólo el próximo punto visible.',heavy:'Con mar gruesa conviene reducir velocidad y aumentar apoyo. Puedes elegir un siguiente paso pequeño.',storm:'Si se siente como una tormenta, no tienes que navegarla a solas. Puedes elegir un pequeño paso o ir directamente a Otra Estación.'}},
  step:{k:'UN PASO',h:'No todo el viaje. Sólo el siguiente.',i:'Elige una acción lo bastante pequeña como para que sea posible ahora.',opts:[['tell','Decírselo a una persona'],['company','Pedir a alguien que se quede conmigo'],['write','Escribir una frase sobre lo que necesito'],['support','Contactar con un servicio de ayuda']],res:{tell:'Tu siguiente paso puede ser una sola frase: “Estoy pasando un mal momento y necesito hablar.”',company:'Puedes pedir compañía sin explicarlo todo: “¿Puedes quedarte conmigo un rato? Ahora mismo no quiero estar solo.”',write:'No necesitas palabras perfectas. Escribe sólo lo que otra persona debería saber para poder acercarse.',support:'Puedes utilizar Otra Estación al final de este recorrido o ir directamente ahora.'}},
  signal:{k:'ENVIAR UNA SEÑAL',h:'No tienes que contar toda la historia.',i:'Elige la primera frase. Faro no la envía ni la guarda. Puedes copiarla o usar el menú de compartir de tu dispositivo.',opts:[['listen','Necesito que alguien me escuche.'],['alone','Ahora mismo no quiero estar solo.'],['hard','Me está costando y necesito un poco de compañía.']],templates:{listen:'Últimamente no estoy muy bien. No necesito que lo soluciones. ¿Puedes escucharme un rato?',alone:'Estoy pasando un momento difícil y ahora mismo no quiero estar solo. ¿Puedes quedarte conmigo o llamarme?',hard:'Ahora mismo todo se siente pesado. Todavía no sé exactamente qué necesito, pero me vendría muy bien un poco de compañía.'},copy:'Copiar señal',share:'Compartir señal',copied:'Señal copiada',ready:'Tu señal está preparada para salir del faro.'},
  answer:{k:'OTRA LUZ RESPONDE',h:'Una señal crea la posibilidad de conexión.',i:'La segunda luz es simbólica: no es una respuesta real de otra persona. Aparece para marcar el momento en que haces tu posición más fácil de ver.',note:'Ahora hay una segunda luz en el horizonte. <b>No porque todo esté resuelto, sino porque una señal puede encontrar respuesta.</b>'},
  station:{k:'OTRA ESTACIÓN',h:'No tienes que navegar a solas.',i:'Ayuda humana y profesional real en España. Elige la estación que se ajuste a lo que necesitas.',cards:[
   ['ESCUCHA','Teléfono de la Esperanza','Atención emocional urgente, gratuita y anónima basada en escucha activa.','Llamar 717 003 717','tel:717003717','Web oficial','https://telefonodelaesperanza.org/intervencion-en-crisis'],
   ['ALICANTE','Teléfono de la Esperanza · Alicante','Contacto local 24h publicado por la sede de Alicante.','Llamar 965 131 122','tel:965131122','Sede Alicante','https://telefonodelaesperanza.org/alicante'],
   ['ADICCIONES + SALUD MENTAL','Proyecto Hombre','Acompañamiento integral y centrado en la persona para adicciones y salud mental. Centro de Alicante: 965 112 125.','Llamar Alicante','tel:965112125','Buscar centro','https://proyectohombre.es/contacta/'],
   ['IDEACIÓN / RIESGO SUICIDA','Línea 024','Servicio nacional, gratuito, confidencial y 24/7 para personas con ideación o riesgo suicida y sus allegados.','Llamar 024','tel:024','024 oficial','https://www.sanidad.gob.es/linea024/'],
   ['EMERGENCIA INMEDIATA','112','Si existe una emergencia vital inmediata, llama ahora a los servicios de emergencia.','Llamar 112','tel:112','', '']
  ],d:'Faro es una experiencia narrativa y de orientación hacia apoyos. No diagnostica, no evalúa riesgo clínico, no ofrece terapia y no sustituye la atención profesional.'}
 }
};
const $=(s,r=document)=>r.querySelector(s), $$=(s,r=document)=>[...r.querySelectorAll(s)];
let lang=document.documentElement.lang==='es'?'es':'en', selectedSignal='listen';
function panel(id,c,center=false){return `<aside class="support-action${center?' center':''}" id="${id}" aria-labelledby="${id}-title"><div class="sa-kicker">${c.k}</div><h3 id="${id}-title">${c.h}</h3><p class="sa-intro">${c.i}</p><div class="sa-options"></div><div class="sa-result" aria-live="polite"></div></aside>`}
function renderChoice(id,c,onPick){const root=$('#'+id),opts=$('.sa-options',root),res=$('.sa-result',root);opts.innerHTML=c.opts.map(([v,l])=>`<button class="sa-btn" type="button" data-value="${v}">${l}</button>`).join('');$$('.sa-btn',opts).forEach(b=>b.onclick=()=>{$$('.sa-btn',opts).forEach(x=>x.classList.remove('active'));b.classList.add('active');res.innerHTML=c.res[b.dataset.value]||'';res.classList.add('show');onPick?.(b.dataset.value,res)});}
function renderSignal(){const c=copy[lang].signal,root=$('#send-signal'),opts=$('.sa-options',root),res=$('.sa-result',root);opts.innerHTML=c.opts.map(([v,l])=>`<button class="sa-btn${v===selectedSignal?' active':''}" type="button" data-value="${v}">${l}</button>`).join('');function show(){const text=c.templates[selectedSignal];res.innerHTML=`<div class="signal-template">${text}</div><div class="signal-actions"><button type="button" data-copy>${c.copy}</button><button type="button" class="primary" data-share>${c.share}</button></div><div class="answer-note" id="answer-note">${copy[lang].answer.note}</div>`;res.classList.add('show');$('[data-copy]',res).onclick=async()=>{try{await navigator.clipboard.writeText(text);$('[data-copy]',res).textContent=c.copied}catch{} activateAnswer()};$('[data-share]',res).onclick=async()=>{if(navigator.share){try{await navigator.share({text});activateAnswer()}catch{}}else{try{await navigator.clipboard.writeText(text)}catch{} activateAnswer()}}}$$('.sa-btn',opts).forEach(b=>b.onclick=()=>{selectedSignal=b.dataset.value;renderSignal();show()});show()}
function activateAnswer(){document.body.classList.add('signal-ready');$('#answer-light')?.classList.add('on');$('#answer-note')?.classList.add('show');$('#answer-symbolic')?.classList.add('show')}
function renderStations(){const c=copy[lang].station,root=$('#another-station');root.querySelector('.station-grid').innerHTML=c.cards.map((x,i)=>`<article class="station-card${i===4?' emergency':''}"><span class="station-type">${x[0]}</span><b>${x[1]}</b><p>${x[2]}</p><div class="station-links"><a href="${x[4]}">${x[3]}</a>${x[5]?`<a href="${x[6]}" target="_blank" rel="noopener">${x[5]}</a>`:''}</div></article>`).join('');root.querySelector('.station-disclaimer').textContent=c.d}
function mount(){
 const coast=$('#coast .stats');coast?.insertAdjacentHTML('afterend',panel('weather-inside',copy[lang].weather));
 const stair=$('#stair .handoff-copy');stair?.insertAdjacentHTML('beforeend',panel('one-step',copy[lang].step,true));
 const beam=$('#beam .beam-copy');beam?.insertAdjacentHTML('beforeend',panel('send-signal',copy[lang].signal));
 const after=$('#afterlight .cta');after?.insertAdjacentHTML('beforebegin',`${panel('another-answer',copy[lang].answer,true)}${panel('another-station',copy[lang].station,true)}`);
 $('#another-answer .sa-options').remove();$('#another-answer .sa-result').outerHTML=`<div class="answer-note" id="answer-symbolic">${copy[lang].answer.note}</div>`;
 $('#another-station .sa-options').outerHTML='<div class="station-grid"></div>';$('#another-station .sa-result').outerHTML='<p class="station-disclaimer"></p>';
 document.body.insertAdjacentHTML('beforeend','<div class="answer-light" id="answer-light" aria-hidden="true"></div>');
 renderChoice('weather-inside',copy[lang].weather,(v)=>{sessionStorage.setItem('faro-weather',v);if(v==='storm')$('#weather-inside .sa-result').insertAdjacentHTML('beforeend',` <a href="#another-station" style="color:#f2d3a2;text-decoration:underline">${lang==='es'?'Ir a Otra Estación':'Go to Another Station'}</a>`)});
 renderChoice('one-step',copy[lang].step,(v)=>{sessionStorage.setItem('faro-one-step',v);if(v==='support')location.hash='another-station'});
 renderSignal();renderStations();
}
function remount(){['weather-inside','one-step','send-signal','another-answer','another-station','answer-light'].forEach(id=>$('#'+id)?.remove());lang=document.documentElement.lang==='es'?'es':'en';mount()}
document.addEventListener('DOMContentLoaded',()=>{mount();new MutationObserver(m=>{if(m.some(x=>x.attributeName==='lang'))remount()}).observe(document.documentElement,{attributes:true,attributeFilter:['lang']})});
})();
