(()=>{
'use strict';

const RADIO_DEMO_URL='https://stream.nightride.fm/chillsynth.mp3';

const COPY={
 en:{
  trigger:{weather:'WEATHER INSIDE →',step:'ONE STEP →',signal:'SEND A SIGNAL →',station:'ANOTHER STATION →'},close:'Close',
  weather:{k:'01 · WEATHER INSIDE',h:'How is the weather inside?',i:'No diagnosis. No score. Just a way to name what you are carrying right now.',opts:[['calm','Calm'],['fog','Fog'],['heavy','Heavy sea'],['storm','Storm']],r:{calm:'Calm is worth noticing too.',fog:'Fog can make the next direction hard to see. You only need the next visible marker.',heavy:'A heavy sea asks for less speed and more support.',storm:'If it feels like a storm, do not navigate it alone.'}},
  step:{k:'02 · ONE STEP',h:'Not the whole journey. Only the next one.',i:'Choose one action small enough to be possible now.',opts:[['tell','Tell one person'],['company','Ask someone to stay with me'],['write','Write one sentence'],['support','Contact support']],r:{tell:'“I am having a hard time and I need to talk.”',company:'“Could you stay with me for a while? I do not want to be alone right now.”',write:'You do not need perfect words. Write only what someone needs to know to come closer.',support:'When you reach Afterlight, Another Station can connect you with real support.'}},
  signal:{k:'03 · SEND A SIGNAL',h:'You do not have to tell the whole story.',i:'Choose a first sentence. Faro does not send or store it.',opts:[['listen','I need someone to listen.'],['alone','I do not want to be alone right now.'],['hard','I am struggling and need company.']],t:{listen:'I am not doing very well lately. I do not need you to fix it. Could you listen for a while?',alone:'I am having a difficult time and I do not want to be alone right now. Could you stay with me or call me?',hard:'Things feel heavy right now. I am not sure what I need yet, but I could really use some company.'},copy:'Copy signal',share:'Share signal',copied:'Signal copied',failed:'Copy failed — select the text and copy it manually.'},
  answer:{k:'04 · ANOTHER LIGHT ANSWERS',h:'A second light appears.',i:'This light is symbolic. It is not a real reply from another person.',r:'There was one light. Now there are two.',close:'Return to the beam'},
  station:{k:'05 · ANOTHER STATION',h:'Find another light.',i:'A night navigation chart toward real human and professional support in Spain.',chart:'SELECT A BEACON',bearing:'NAVIGATION CHART · SPAIN',choose:'Select a station to reveal its route.',call:'CALL THIS STATION',cards:[
   ['LISTEN','Teléfono de la Esperanza','Urgent, free, anonymous emotional support and active listening.','717 003 717','tel:717003717',24,29],
   ['LOCAL LIGHT · ALICANTE','Teléfono de la Esperanza · Alicante','Local contact published by the Alicante centre.','965 131 122','tel:965131122',62,20],
   ['RECOVERY','Proyecto Hombre · Alicante','Person-centred support for addictions and emotional health.','965 112 125','tel:965112125',43,58],
   ['CRISIS','Línea 024','National, free, confidential, 24/7 support.','024','tel:024',76,57],
   ['EMERGENCY','112','For an immediate life-threatening emergency.','112','tel:112',20,76]
  ],d:'Faro does not diagnose, assess clinical risk, provide therapy or replace professional care.',doors:'THE LAST LIGHTHOUSE CONTINUES',listen:'02 · LISTEN',learn:'03 · LEARN',connect:'05 · CONNECT'},
  listen:{k:'02 · LISTEN',h:'Lighthouse Radio',i:'A listening room for live sound, future real stories and short signals.',live:'LIVE DEMO RADIO',station:'Chillsynth · Nightride FM',demo:'External radio is used only to prove the listening experience works. Final editorial audio will be selected separately.',play:'PLAY LIVE',pause:'PAUSE',lead:'Choose how a signal can be heard.',cards:[['I’VE BEEN THE LIGHTHOUSE','Real first-person stories from people who asked for help.','STORY'],['I’VE SEEN THE SIGNAL','Friends and relatives describing what they noticed and how they stayed.','PERSPECTIVE'],['I ANSWER SIGNALS','Volunteers and professionals on what listening actually means.','CONVERSATION'],['I’M STILL FINDING MY WAY','Stories without a forced happy ending.','ONGOING']],signals:'6 SECOND SIGNALS',signalItems:['What helped me stay was…','I wish someone had told me…','Asking for help started when…'],sessions:'LIGHTHOUSE PODCAST / SESSIONS',sessionItems:[['01','How to ask for help','Editorial prototype'],['02','How to listen without fixing','Editorial prototype'],['03','When addiction and emotional pain meet','Editorial prototype']],note:'No invented testimony is published. Real voices require explicit consent, safeguarding and the right to withdraw.',back:'Back to navigation chart'},
  learn:{k:'03 · LEARN',h:'Listening is a skill.',i:'Short workshops inside the lighthouse — situations, choices and useful feedback.',modules:[
   {id:'stay',n:'01',h:'HOW TO STAY',p:'Someone says: “I can’t do this anymore.”',q:'Which response feels like someone stayed?',opts:[['fix','“Come on, don’t think like that. You have so many good things.”'],['stay','“It sounds like you’re going through something very hard. I’m here. Tell me.”']],r:{fix:'Trying to fix the feeling quickly can close the signal. Listening starts by staying with what the person is actually saying.',stay:'This acknowledges the difficulty, stays present and opens space for the person to continue.'}},
   {id:'ask',n:'02',h:'THE FIRST TEN WORDS',p:'You are worried about someone who has become distant.',q:'Which opening makes more room for an honest answer?',opts:[['soft','“You seem different lately. How are you — really?”'],['push','“What is wrong with you? You need to tell me.”']],r:{soft:'Specific observation plus an open question can make the signal easier to send.',push:'Pressure can make someone retreat. Ask clearly, then leave room for the answer.'}},
   {id:'notice',n:'03',h:'NOTICE THE SIGNAL',p:'A friend says: “I’m just tired. It’s nothing.”',q:'What can you do without trying to diagnose them?',opts:[['twice','Ask again gently and stay available.'],['label','Tell them what condition you think they have.']],r:{twice:'You do not need a diagnosis to notice a change. Asking twice can show that the first answer did not have to end the conversation.',label:'Diagnosis is not the role of this experience. Notice, ask, listen and connect to professional support when needed.'}},
   {id:'station',n:'04',h:'BRING IN ANOTHER STATION',p:'Listening does not mean carrying everything alone.',q:'When should another source of support enter the route?',opts:[['share','When the person wants more help, the situation exceeds what you can hold, or there is immediate danger.'],['solo','Only after you have solved the situation yourself.']],r:{share:'Connection is part of listening. A trusted person, professional service or emergency resource can become another station.',solo:'You are not required to solve everything. Good support can include knowing when to connect another station.'}}
  ],back:'Back to navigation chart'},
  nav:{listen:'02 LISTEN',learn:'03 LEARN',connect:'05 CONNECT'}
 },
 es:{
  trigger:{weather:'¿QUÉ TIEMPO HACE POR DENTRO? →',step:'UN PASO →',signal:'ENVIAR UNA SEÑAL →',station:'OTRA ESTACIÓN →'},close:'Cerrar',
  weather:{k:'01 · EL TIEMPO POR DENTRO',h:'¿Qué tiempo hace por dentro?',i:'Sin diagnóstico. Sin puntuación. Sólo una forma de nombrar lo que llevas contigo ahora mismo.',opts:[['calm','Calma'],['fog','Niebla'],['heavy','Mar gruesa'],['storm','Tormenta']],r:{calm:'También merece la pena notar la calma.',fog:'La niebla puede dificultar ver la siguiente dirección. Sólo necesitas el próximo punto visible.',heavy:'Con mar gruesa conviene reducir velocidad y aumentar apoyo.',storm:'Si se siente como una tormenta, no tienes que navegarla a solas.'}},
  step:{k:'02 · UN PASO',h:'No todo el viaje. Sólo el siguiente.',i:'Elige una acción lo bastante pequeña como para que sea posible ahora.',opts:[['tell','Decírselo a una persona'],['company','Pedir compañía'],['write','Escribir una frase'],['support','Contactar con ayuda']],r:{tell:'“Estoy pasando un mal momento y necesito hablar.”',company:'“¿Puedes quedarte conmigo un rato? Ahora mismo no quiero estar solo.”',write:'No necesitas palabras perfectas. Escribe sólo lo que alguien necesita saber para acercarse.',support:'Cuando llegues a Afterlight, Otra Estación podrá conectarte con ayuda real.'}},
  signal:{k:'03 · ENVIAR UNA SEÑAL',h:'No tienes que contar toda la historia.',i:'Elige una primera frase. Faro no la envía ni la guarda.',opts:[['listen','Necesito que alguien me escuche.'],['alone','No quiero estar solo ahora mismo.'],['hard','Me está costando y necesito compañía.']],t:{listen:'Últimamente no estoy muy bien. No necesito que lo soluciones. ¿Puedes escucharme un rato?',alone:'Estoy pasando un momento difícil y ahora mismo no quiero estar solo. ¿Puedes quedarte conmigo o llamarme?',hard:'Ahora mismo todo se siente pesado. Todavía no sé exactamente qué necesito, pero me vendría bien compañía.'},copy:'Copiar señal',share:'Compartir señal',copied:'Señal copiada',failed:'No se pudo copiar — selecciona el texto y cópialo manualmente.'},
  answer:{k:'04 · OTRA LUZ RESPONDE',h:'Aparece una segunda luz.',i:'Esta luz es simbólica. No es una respuesta real de otra persona.',r:'Había una sola luz. Ahora hay dos.',close:'Volver al haz'},
  station:{k:'05 · OTRA ESTACIÓN',h:'Encuentra otra luz.',i:'Una carta nocturna de navegación hacia ayuda humana y profesional real en España.',chart:'SELECCIONA UNA BALIZA',bearing:'CARTA DE NAVEGACIÓN · ESPAÑA',choose:'Selecciona una estación para revelar su ruta.',call:'LLAMAR A ESTA ESTACIÓN',cards:[
   ['ESCUCHA','Teléfono de la Esperanza','Atención emocional urgente, gratuita y anónima basada en escucha activa.','717 003 717','tel:717003717',24,29],
   ['LUZ LOCAL · ALICANTE','Teléfono de la Esperanza · Alicante','Contacto local publicado por la sede de Alicante.','965 131 122','tel:965131122',62,20],
   ['RECUPERACIÓN','Proyecto Hombre · Alicante','Acompañamiento centrado en la persona para adicciones y salud emocional.','965 112 125','tel:965112125',43,58],
   ['CRISIS','Línea 024','Servicio nacional, gratuito, confidencial y 24/7.','024','tel:024',76,57],
   ['EMERGENCIA','112','Para una emergencia vital inmediata.','112','tel:112',20,76]
  ],d:'Faro no diagnostica, no evalúa riesgo clínico, no ofrece terapia y no sustituye la atención profesional.',doors:'THE LAST LIGHTHOUSE CONTINÚA',listen:'02 · LISTEN',learn:'03 · LEARN',connect:'05 · CONNECT'},
  listen:{k:'02 · LISTEN',h:'Lighthouse Radio',i:'Una sala de escucha para sonido en directo, futuras historias reales y señales breves.',live:'RADIO DEMO EN DIRECTO',station:'Chillsynth · Nightride FM',demo:'La radio externa se usa sólo para demostrar que la experiencia de escucha funciona. El audio editorial final se seleccionará por separado.',play:'REPRODUCIR',pause:'PAUSA',lead:'Elige cómo puede escucharse una señal.',cards:[['I’VE BEEN THE LIGHTHOUSE','Historias reales en primera persona de quienes pidieron ayuda.','HISTORIA'],['I’VE SEEN THE SIGNAL','Familiares y amigos explicando qué percibieron y cómo permanecieron cerca.','PERSPECTIVA'],['I ANSWER SIGNALS','Voluntarios y profesionales sobre qué significa escuchar de verdad.','CONVERSACIÓN'],['I’M STILL FINDING MY WAY','Historias sin obligarlas a terminar con un final feliz.','EN PROCESO']],signals:'6 SECOND SIGNALS',signalItems:['Lo que me ayudó a quedarme fue…','Ojalá alguien me hubiera dicho…','Pedir ayuda empezó cuando…'],sessions:'LIGHTHOUSE PODCAST / SESSIONS',sessionItems:[['01','Cómo pedir ayuda','Prototipo editorial'],['02','Cómo escuchar sin arreglar','Prototipo editorial'],['03','Cuando adicción y dolor emocional se encuentran','Prototipo editorial']],note:'No publicamos testimonios inventados. Las voces reales requieren consentimiento explícito, salvaguarda y derecho a retirar la publicación.',back:'Volver a la carta de navegación'},
  learn:{k:'03 · LEARN',h:'Escuchar es una habilidad.',i:'Talleres breves dentro del faro: situaciones, decisiones y feedback útil.',modules:[
   {id:'stay',n:'01',h:'CÓMO QUEDARSE',p:'Alguien dice: “No puedo más.”',q:'¿Qué respuesta se siente como si alguien se quedara?',opts:[['fix','“Venga, no pienses así. Tienes muchas cosas buenas.”'],['stay','“Parece que estás pasando por algo muy duro. Estoy aquí. Cuéntame.”']],r:{fix:'Intentar arreglar rápidamente lo que siente puede cerrar la señal. Escuchar empieza por quedarse con lo que la persona está diciendo.',stay:'Esta respuesta reconoce la dificultad, permanece presente y abre espacio para que la persona continúe.'}},
   {id:'ask',n:'02',h:'LAS PRIMERAS DIEZ PALABRAS',p:'Te preocupa alguien que se ha vuelto más distante.',q:'¿Qué apertura deja más espacio para una respuesta sincera?',opts:[['soft','“Te noto diferente últimamente. ¿Cómo estás, de verdad?”'],['push','“¿Qué te pasa? Tienes que contármelo.”']],r:{soft:'Una observación concreta y una pregunta abierta pueden facilitar que aparezca la señal.',push:'La presión puede hacer que alguien se cierre. Pregunta con claridad y deja espacio para responder.'}},
   {id:'notice',n:'03',h:'RECONOCER LA SEÑAL',p:'Un amigo dice: “Sólo estoy cansado. No es nada.”',q:'¿Qué puedes hacer sin intentar diagnosticar?',opts:[['twice','Volver a preguntar con suavidad y seguir disponible.'],['label','Decirle qué condición crees que tiene.']],r:{twice:'No necesitas diagnosticar para notar un cambio. Preguntar dos veces puede mostrar que la primera respuesta no tenía que cerrar la conversación.',label:'Diagnosticar no es la función de esta experiencia. Observa, pregunta, escucha y conecta con ayuda profesional cuando sea necesario.'}},
   {id:'station',n:'04',h:'TRAER OTRA ESTACIÓN',p:'Escuchar no significa cargar con todo a solas.',q:'¿Cuándo debe entrar otra fuente de ayuda en la ruta?',opts:[['share','Cuando la persona quiere más ayuda, la situación supera lo que puedes sostener o existe peligro inmediato.'],['solo','Sólo después de haber resuelto tú mismo la situación.']],r:{share:'Conectar también forma parte de escuchar. Una persona de confianza, un profesional o un recurso de emergencia pueden convertirse en otra estación.',solo:'No tienes que resolverlo todo. Apoyar bien también implica saber cuándo conectar otra estación.'}}
  ],back:'Volver a la carta de navegación'},
  nav:{listen:'02 LISTEN',learn:'03 LEARN',connect:'05 CONNECT'}
 }
};

const q=(s,r=document)=>r.querySelector(s);
const qa=(s,r=document)=>[...r.querySelectorAll(s)];
const ACTION_BY_SECTION={coast:'weather',stair:'step',beam:'signal',afterlight:'station'};
let lang='en',currentSection='hero',activeAction=null,signal='listen',scrollLockY=0,locked=false,answerSeen=false,radio=null,activeLearn='stay';

function shell(){
 document.body.insertAdjacentHTML('beforeend',`
  <div class="support-field-signal" id="support-field-signal" aria-hidden="true"><i></i><b></b></div>
  <button class="support-trigger" id="support-trigger" type="button" aria-expanded="false" hidden><i aria-hidden="true"></i><span></span></button>
  <aside class="support-deck" id="support-deck" aria-hidden="true">
   <div class="support-deck-head"><div class="support-mini">LIGHT → SIGNAL → ANSWER → CONNECTION</div><button id="support-close" type="button">×</button></div>
   <nav class="support-door-dock" id="support-door-dock" hidden></nav>
   <div class="support-content" id="support-content"></div>
  </aside>
  <div class="answer-event" id="answer-event" aria-hidden="true">
   <div class="answer-sky"><i class="answer-core"></i><i class="answer-halo h1"></i><i class="answer-halo h2"></i><i class="answer-beam"></i><i class="answer-beam secondary"></i></div>
   <div class="answer-copy" id="answer-copy"></div>
  </div>`);
 q('#support-trigger').addEventListener('click',()=>openAction(ACTION_BY_SECTION[currentSection]));
 q('#support-close').addEventListener('click',closeDeck);
 document.addEventListener('keydown',e=>{if(e.key==='Escape'){if(q('#answer-event').classList.contains('show'))closeAnswer();else closeDeck()}});
 document.addEventListener('wheel',blockScroll,{passive:false,capture:true});
 document.addEventListener('touchmove',blockScroll,{passive:false,capture:true});
 document.addEventListener('keydown',blockKeys,{capture:true});
 trackSections();
}
function blockScroll(e){if(locked)e.preventDefault()}
function blockKeys(e){if(!locked)return;if(['ArrowUp','ArrowDown','PageUp','PageDown','Home','End',' '].includes(e.key))e.preventDefault()}
function lockScroll(){if(locked)return;scrollLockY=scrollY;locked=true;document.documentElement.classList.add('support-scroll-locked')}
function unlockScroll(){if(!locked)return;locked=false;document.documentElement.classList.remove('support-scroll-locked');requestAnimationFrame(()=>scrollTo(0,scrollLockY))}
function openAction(action){if(!action)return;activeAction=action;lockScroll();renderAction();const deck=q('#support-deck');deck.classList.toggle('station-mode',action==='station');deck.classList.toggle('room-mode',action==='listen'||action==='learn');deck.classList.add('open');deck.setAttribute('aria-hidden','false');q('#support-trigger').setAttribute('aria-expanded','true');renderDoorDock();q('#support-close').focus({preventScroll:true})}
function closeDeck(){const deck=q('#support-deck');if(!deck?.classList.contains('open'))return;stopRadio();deck.classList.remove('open','station-mode','room-mode');deck.setAttribute('aria-hidden','true');q('#support-door-dock').hidden=true;q('#support-trigger').setAttribute('aria-expanded','false');unlockScroll();updateTrigger()}
function trackSections(){const sections=qa('.sec');let ticking=false;const update=()=>{ticking=false;const y=innerHeight*.48;let best=sections[0],dist=Infinity;sections.forEach(s=>{const r=s.getBoundingClientRect(),d=Math.abs((r.top+r.height*.38)-y);if(d<dist){dist=d;best=s}});setSection(best?.id||'hero')};const schedule=()=>{if(!ticking){ticking=true;requestAnimationFrame(update)}};addEventListener('scroll',schedule,{passive:true});addEventListener('resize',schedule,{passive:true});update()}
function setSection(id){if(id===currentSection)return;currentSection=id;updateTrigger(true)}
function updateTrigger(arrival=false){lang=document.documentElement.lang==='es'?'es':'en';const action=ACTION_BY_SECTION[currentSection],btn=q('#support-trigger'),flight=q('#support-field-signal');if(!action||q('#support-deck').classList.contains('open')||q('#answer-event').classList.contains('show')){btn.hidden=true;btn.classList.remove('visible','signal-arrival');flight.classList.remove('fly');return}q('span',btn).textContent=COPY[lang].trigger[action];btn.dataset.action=action;btn.hidden=false;btn.classList.remove('signal-arrival');requestAnimationFrame(()=>{btn.classList.add('visible');if(arrival){void btn.offsetWidth;btn.classList.add('signal-arrival');flight.classList.remove('fly');void flight.offsetWidth;flight.classList.add('fly')}})}
function renderAction(){lang=document.documentElement.lang==='es'?'es':'en';const c=COPY[lang][activeAction],root=q('#support-content');q('#support-close').setAttribute('aria-label',COPY[lang].close);if(activeAction==='weather'||activeAction==='step'){root.innerHTML=`<div class="deck-k">${c.k}</div><h3>${c.h}</h3><p>${c.i}</p><div class="deck-options">${c.opts.map(([v,l])=>`<button type="button" data-choice="${v}">${l}</button>`).join('')}</div><div class="deck-result" aria-live="polite"></div>`;qa('[data-choice]',root).forEach(b=>b.onclick=()=>{qa('[data-choice]',root).forEach(x=>x.classList.remove('on'));b.classList.add('on');q('.deck-result',root).textContent=c.r[b.dataset.choice];q('.deck-result',root).classList.add('show');sessionStorage.setItem('faro-'+activeAction,b.dataset.choice)});return}if(activeAction==='signal'){renderSignal(root,c);return}if(activeAction==='station'){renderStation(root,c);return}if(activeAction==='listen'){renderListen(root,c);return}if(activeAction==='learn'){renderLearn(root,c)}}
function renderDoorDock(){const dock=q('#support-door-dock');if(!['station','listen','learn'].includes(activeAction)){dock.hidden=true;return}const n=COPY[lang].nav;dock.hidden=false;dock.innerHTML=`<button data-door="listen" class="${activeAction==='listen'?'on':''}"><i></i>${n.listen}</button><button data-door="learn" class="${activeAction==='learn'?'on':''}"><i></i>${n.learn}</button><button data-door="station" class="${activeAction==='station'?'on':''}"><i></i>${n.connect}</button>`;qa('[data-door]',dock).forEach(b=>b.onclick=()=>openRoom(b.dataset.door))}
function renderSignal(root,c){root.innerHTML=`<div class="deck-k">${c.k}</div><h3>${c.h}</h3><p>${c.i}</p><div class="deck-options">${c.opts.map(([v,l])=>`<button type="button" data-signal="${v}" class="${v===signal?'on':''}">${l}</button>`).join('')}</div><div class="signal-template" tabindex="0">${c.t[signal]}</div><div class="signal-actions"><button type="button" id="copy-signal">${c.copy}</button><button type="button" id="share-signal">${c.share}</button></div><div class="signal-status" aria-live="polite"></div>`;qa('[data-signal]',root).forEach(b=>b.onclick=()=>{signal=b.dataset.signal;renderSignal(root,c)});q('#copy-signal').onclick=async()=>{try{await navigator.clipboard.writeText(c.t[signal]);q('#copy-signal').textContent=c.copied;showAnswer()}catch{q('.signal-status',root).textContent=c.failed}};q('#share-signal').onclick=async()=>{try{if(navigator.share)await navigator.share({text:c.t[signal]});else await navigator.clipboard.writeText(c.t[signal]);showAnswer()}catch{q('.signal-status',root).textContent=c.failed}}}
function showAnswer(){const c=COPY[lang].answer;answerSeen=true;stopRadio();const deck=q('#support-deck');deck.classList.remove('open','station-mode','room-mode');deck.setAttribute('aria-hidden','true');q('#support-door-dock').hidden=true;q('#support-trigger').hidden=true;const root=q('#answer-copy');root.innerHTML=`<div class="deck-k">${c.k}</div><h3>${c.h}</h3><p>${c.i}</p><strong>${c.r}</strong><button type="button" id="answer-return">${c.close}</button>`;const event=q('#answer-event');event.classList.remove('show');event.setAttribute('aria-hidden','false');void event.offsetWidth;event.classList.add('show');q('#answer-return').onclick=closeAnswer}
function closeAnswer(){const event=q('#answer-event');if(!event.classList.contains('show'))return;event.classList.remove('show');event.setAttribute('aria-hidden','true');unlockScroll();updateTrigger()}
function renderStation(root,c){
 const points=c.cards.map((x,i)=>`<button type="button" class="station-node${i>=3?' urgent':''}" data-station="${i}" style="--x:${x[5]}%;--y:${x[6]}%"><i></i><span>${String(i+1).padStart(2,'0')}</span><b>${x[0]}</b></button>`).join('');
 root.innerHTML=`<div class="deck-k">${c.k}</div><h3>${c.h}</h3><p>${c.i}</p><div class="station-chart-v2"><div class="chart-meta"><span>${c.bearing}</span><b>${c.chart}</b></div><svg viewBox="0 0 100 100" preserveAspectRatio="none" aria-hidden="true"><path d="M24 29 L62 20 L43 58 L76 57 L20 76 L24 29"/><path d="M43 58 L20 76"/></svg>${points}<div class="station-radar r1"></div><div class="station-radar r2"></div></div><div class="station-detail" id="station-detail"><span>${c.choose}</span></div><small class="station-disclaimer">${c.d}</small><div class="next-rooms hero-doors"><span>${c.doors}</span><button type="button" data-room="listen"><i></i><b>${c.listen}</b><small>LIGHTHOUSE RADIO / LISTENING ROOM</small></button><button type="button" data-room="learn"><i></i><b>${c.learn}</b><small>MICRO-WORKSHOPS / LIGHTHOUSE SESSIONS</small></button></div>`;
 qa('[data-station]',root).forEach(b=>b.onclick=()=>selectStation(Number(b.dataset.station)));
 qa('[data-room]',root).forEach(b=>b.onclick=()=>openRoom(b.dataset.room));
}
function selectStation(index){const c=COPY[lang].station,x=c.cards[index],root=q('#support-content');qa('[data-station]',root).forEach((b,i)=>b.classList.toggle('on',i===index));q('#station-detail').innerHTML=`<div class="station-detail-beacon"><i></i><span>${x[0]}</span></div><div><h4>${x[1]}</h4><p>${x[2]}</p></div><a href="${x[4]}"><small>${c.call}</small><b>${x[3]}</b></a>`}
function openRoom(room){stopRadio();activeAction=room;const deck=q('#support-deck');deck.classList.toggle('station-mode',room==='station');deck.classList.toggle('room-mode',room!=='station');deck.classList.add('open');renderAction();renderDoorDock()}
function renderListen(root,c){
 root.innerHTML=`<div class="deck-k">${c.k}</div><h3>${c.h}</h3><p>${c.i}</p><section class="radio-console"><div class="radio-orbit"><i></i><b></b></div><div class="radio-copy"><span>${c.live}</span><h4>${c.station}</h4><p>${c.demo}</p></div><button type="button" id="radio-toggle"><i></i><span>${c.play}</span></button><audio id="lighthouse-radio" preload="none" src="${RADIO_DEMO_URL}"></audio><div class="radio-wave" aria-hidden="true">${'<i></i>'.repeat(18)}</div></section><strong class="room-lead">${c.lead}</strong><div class="listen-grid">${c.cards.map(([h,p,t])=>`<article><span>${t}</span><i aria-hidden="true"></i><h4>${h}</h4><p>${p}</p><b>→</b></article>`).join('')}</div><section class="signal-strip"><div><span>FL W 6s</span><h4>${c.signals}</h4></div>${c.signalItems.map((x,i)=>`<button type="button"><b>0${i+1}</b><span>${x}</span><i></i></button>`).join('')}</section><section class="session-list"><span>${c.sessions}</span>${c.sessionItems.map(([n,h,s])=>`<article><b>${n}</b><h4>${h}</h4><small>${s}</small><i>→</i></article>`).join('')}</section><p class="room-note">${c.note}</p><button type="button" class="room-back">← ${c.back}</button>`;
 radio=q('#lighthouse-radio');const toggle=q('#radio-toggle');toggle.onclick=async()=>{if(radio.paused){try{await radio.play();toggle.classList.add('playing');q('span',toggle).textContent=c.pause;q('.radio-console').classList.add('playing')}catch{q('span',toggle).textContent=c.play}}else{radio.pause();toggle.classList.remove('playing');q('span',toggle).textContent=c.play;q('.radio-console').classList.remove('playing')}};
 q('.room-back',root).onclick=()=>openRoom('station');
}
function stopRadio(){if(radio&&!radio.paused){radio.pause()}radio=null}
function renderLearn(root,c){
 const current=c.modules.find(x=>x.id===activeLearn)||c.modules[0];
 root.innerHTML=`<div class="deck-k">${c.k}</div><h3>${c.h}</h3><p>${c.i}</p><div class="workshop-nav">${c.modules.map(m=>`<button type="button" data-module="${m.id}" class="${m.id===current.id?'on':''}"><span>${m.n}</span><b>${m.h}</b></button>`).join('')}</div><section class="workshop-stage"><div class="workshop-bearing"><i></i><span>${current.n} / 04</span></div><blockquote>${current.p}</blockquote><strong>${current.q}</strong><div class="learn-options">${current.opts.map(([v,l])=>`<button type="button" data-learn="${v}">${l}</button>`).join('')}</div><div class="deck-result learn-result" aria-live="polite"></div></section><button type="button" class="room-back">← ${c.back}</button>`;
 qa('[data-module]',root).forEach(b=>b.onclick=()=>{activeLearn=b.dataset.module;renderLearn(root,c)});
 qa('[data-learn]',root).forEach(b=>b.onclick=()=>{qa('[data-learn]',root).forEach(x=>x.classList.remove('on'));b.classList.add('on');const r=q('.learn-result',root);r.textContent=current.r[b.dataset.learn];r.classList.add('show')});
 q('.room-back',root).onclick=()=>openRoom('station');
}

new MutationObserver(m=>{if(m.some(x=>x.attributeName==='lang')){lang=document.documentElement.lang==='es'?'es':'en';if(q('#support-deck').classList.contains('open')){renderAction();renderDoorDock()}if(q('#answer-event').classList.contains('show'))showAnswer();updateTrigger()}}).observe(document.documentElement,{attributes:true,attributeFilter:['lang']});
document.addEventListener('DOMContentLoaded',()=>{shell();updateTrigger();window.__FARO_SUPPORT_QA__={version:'overlay-v5',outsidePage:()=>!q('#support-trigger')?.closest('.page')&&!q('#support-deck')?.closest('.page'),locked:()=>locked,currentSection:()=>currentSection,answerSeen:()=>answerSeen,radioDemo:()=>RADIO_DEMO_URL,activeAction:()=>activeAction}});
})();