const { test, expect } = require('@playwright/test');
const fs = require('fs');

test.setTimeout(240000);
const scenes=[['opening','hero'],['coast','coast'],['keeper','keeper'],['stair','stair'],['machine','machine'],['beam','beam'],['afterlight','afterlight']];
async function collectErrors(page){const errors=[];page.on('console',m=>{if(m.type()==='error')errors.push(m.text())});page.on('pageerror',e=>errors.push(e.message));return errors}
async function openSite(page){await page.goto('/',{waitUntil:'domcontentloaded',timeout:45000});await page.waitForFunction(()=>window.__FARO_QA__?.ready===true,null,{timeout:60000});await page.waitForTimeout(900)}
async function captureViewport(cdp,path){const shot=await cdp.send('Page.captureScreenshot',{format:'png',fromSurface:true,captureBeyondViewport:false});fs.writeFileSync(path,Buffer.from(shot.data,'base64'))}
async function jumpToScene(page,id,offsetFactor=.22){const r=await page.evaluate(({id,offsetFactor})=>{const e=document.getElementById(id);if(!e)return{ok:false,id};const y=e.offsetTop+Math.min(e.offsetHeight*offsetFactor,500);scrollTo(0,y);return{ok:true,id,y}},{id,offsetFactor});expect(r.ok,`Missing scene #${id}`).toBeTruthy()}
for(const viewport of [{name:'desktop',width:1440,height:1000},{name:'mobile',width:390,height:844}]){test(`${viewport.name}: Kage-architecture smoke + visual evidence`,async({page})=>{await page.setViewportSize({width:viewport.width,height:viewport.height});const errors=await collectErrors(page);await openSite(page);await expect(page.locator('body')).toContainText(/THE LAST LIGHTHOUSE/i);await expect(page.locator('#gl')).toBeVisible();const a=await page.evaluate(()=>({plateA:!!document.querySelector('#plateA'),plateB:!!document.querySelector('#plateB'),depthGrade:!!document.querySelector('#depthGrade'),fgSky:!!document.querySelector('#fg-sky'),webgl:!!(document.querySelector('#gl')?.getContext('webgl2')||document.querySelector('#gl')?.getContext('webgl')),runtime:window.__FARO_QA__,pageHeight:document.documentElement.scrollHeight,viewportHeight:innerHeight}));expect(a.plateA).toBeFalsy();expect(a.plateB).toBeFalsy();expect(a.depthGrade).toBeFalsy();expect(a.fgSky).toBeTruthy();expect(a.webgl).toBeTruthy();expect(String(a.runtime?.world||'')).toMatch(/^single-webgl/);expect(a.runtime?.plates).toBe(false);expect(a.runtime?.ready).toBe(true);expect(a.pageHeight).toBeGreaterThan(a.viewportHeight*4);fs.mkdirSync('qa-artifacts',{recursive:true});const cdp=await page.context().newCDPSession(page);try{for(const[name,id]of scenes){await jumpToScene(page,id);await page.waitForTimeout(650);await captureViewport(cdp,`qa-artifacts/${viewport.name}-${name}.png`)}}finally{await cdp.detach().catch(()=>{})}expect(errors,errors.join('\n')).toEqual([])})}
test('desktop: foreground lifecycle and Machine live viewport',async({page})=>{await page.setViewportSize({width:1440,height:1000});await openSite(page);await jumpToScene(page,'machine',.65);await page.waitForTimeout(1100);const s=await page.evaluate(()=>({noFullScreenPlates:!document.querySelector('#plateA,#plateB,#depthGrade'),text:document.querySelector('#machine')?.innerText||'',runtime:window.__FARO_QA__,webgl:!!(document.querySelector('#gl')?.getContext('webgl2')||document.querySelector('#gl')?.getContext('webgl'))}));expect(s.text.toLowerCase()).toContain('machine');expect(s.noFullScreenPlates).toBeTruthy();expect(s.webgl).toBeTruthy();expect(s.runtime?.ready).toBeTruthy();fs.mkdirSync('qa-artifacts',{recursive:true});const cdp=await page.context().newCDPSession(page);try{await captureViewport(cdp,'qa-artifacts/desktop-machine-close.png')}finally{await cdp.detach().catch(()=>{})}});
