const {test,expect}=require('@playwright/test');
test.setTimeout(180000);
const sceneIds=['hero','coast','keeper','stair','machine','beam','afterlight'];
async function openStory(page){await page.goto('/storytelling.html',{waitUntil:'domcontentloaded',timeout:45000});await page.waitForFunction(()=>window.__FARO_QA__?.ready===true&&window.__FARO_PHASE_A__?.version==='phase-a-2',null,{timeout:60000});await page.waitForSelector('#support-trigger',{state:'attached'});await page.waitForTimeout(250)}
async function jump(page,id,f=.38){await page.evaluate(({id,f})=>{const e=document.getElementById(id);scrollTo(0,e.offsetTop+Math.min(e.offsetHeight*f,520))},{id,f});await page.waitForTimeout(550)}
async function geometry(page){return page.evaluate(sceneIds=>({scrollHeight:document.documentElement.scrollHeight,bodyHeight:document.body.scrollHeight,scrollWidth:document.documentElement.scrollWidth,clientWidth:document.documentElement.clientWidth,scenes:Object.fromEntries(sceneIds.map(id=>{const e=document.getElementById(id),r=e.getBoundingClientRect();return[id,{offsetTop:e.offsetTop,offsetHeight:e.offsetHeight,width:r.width,height:r.height}]})),supportInsidePage:!!document.querySelector('.page #support-trigger,.page #support-deck,.page #answer-event,.page #support-field-signal,.page #phasea-overlay'),supportInsideSection:!!document.querySelector('.sec #support-trigger,.sec #support-deck,.sec #answer-event,.sec #support-field-signal,.sec #phasea-overlay')}),sceneIds)}
async function grantClipboard(page){await page.context().grantPermissions(['clipboard-read','clipboard-write'])}

test('Rule 0: support and Phase A never change Faro geometry or closed scroll position',async({page})=>{await page.setViewportSize({width:1440,height:1000});await openStory(page);await jump(page,'coast');const before=await geometry(page),y0=await page.evaluate(()=>scrollY);expect(before.supportInsidePage).toBeFalsy();expect(before.supportInsideSection).toBeFalsy();await page.locator('#support-trigger').click();await expect(page.locator('#support-deck')).toHaveClass(/open/);expect(await geometry(page)).toEqual(before);await page.mouse.wheel(0,900);await page.waitForTimeout(120);expect(await page.evaluate(()=>scrollY)).toBe(y0);await page.locator('#support-close').click();await page.waitForTimeout(160);expect(await geometry(page)).toEqual(before);expect(await page.evaluate(()=>scrollY)).toBe(y0)});

test('Progressive reveal keeps silence chapters and moving field signals',async({page})=>{await page.setViewportSize({width:1440,height:1000});await openStory(page);await jump(page,'coast');await expect(page.locator('#support-trigger')).toContainText('WEATHER INSIDE');await expect(page.locator('#support-field-signal')).toHaveClass(/fly/);await jump(page,'keeper');await expect(page.locator('#support-trigger')).toBeHidden();await jump(page,'stair');await expect(page.locator('#support-trigger')).toContainText('ONE STEP');await jump(page,'machine');await expect(page.locator('#support-trigger')).toBeHidden();await jump(page,'beam');await expect(page.locator('#support-trigger')).toContainText('SEND A SIGNAL');await jump(page,'afterlight');await expect(page.locator('#support-trigger')).toContainText('ANOTHER STATION')});

test('Signal creates symbolic Another Light and Afterlight exposes five real navigation beacons',async({page})=>{await grantClipboard(page);await page.setViewportSize({width:1440,height:1000});await openStory(page);await jump(page,'beam');await page.locator('#support-trigger').click();await expect(page.locator('.signal-template')).toContainText('Could you listen for a while?');await page.locator('#copy-signal').click();await expect(page.locator('#answer-event')).toHaveClass(/show/);await expect(page.locator('#answer-copy')).toContainText('A second light appears');await expect(page.locator('#answer-copy')).toContainText('symbolic');await expect(page.locator('#phasea-answer-listen')).toContainText('YOU ARE NOT THE ONLY SIGNAL');await expect(page.locator('.answer-beam.secondary')).toBeAttached();await page.waitForTimeout(2900);await page.locator('#answer-return').click();await page.waitForTimeout(180);await jump(page,'afterlight');await page.locator('#support-trigger').click();await expect(page.locator('.station-chart-v2')).toBeVisible();await expect(page.locator('.station-node')).toHaveCount(5);await page.locator('[data-station="2"]').click();await expect(page.locator('#station-detail')).toContainText('Proyecto Hombre');await page.locator('[data-station="3"]').click();await expect(page.locator('#station-detail')).toContainText('024');await page.locator('[data-station="4"]').click();await expect(page.locator('#station-detail')).toContainText('112')});

test('LISTEN route leaves legacy deck and opens differentiated Phase A Listening Room',async({page})=>{await page.setViewportSize({width:1440,height:1000});await openStory(page);await jump(page,'afterlight');await page.locator('#support-trigger').click();await expect(page.locator('.hero-doors [data-room="listen"]')).toBeVisible();await page.locator('.hero-doors [data-room="listen"]').click();await expect(page.locator('#phasea-overlay')).toHaveClass(/open/);await expect(page.locator('#phasea-overlay')).toHaveAttribute('data-room','listen');await expect(page.locator('.listen-hero h2')).toContainText('SOMEONE IS SPEAKING');await expect(page.locator('#record-hero')).toContainText('RECORD YOUR SIGNAL');await expect(page.locator('.listen-orbits')).toContainText('PODCAST WORKSHOP');await expect(page.locator('#support-deck')).not.toHaveClass(/open/)});

test('Mobile ES keeps navigation chart, LEARN and Phase A within viewport',async({page})=>{await page.setViewportSize({width:390,height:844});await openStory(page);const before=await geometry(page);await page.locator('[data-lang="es"]').click();await jump(page,'afterlight');await page.locator('#support-trigger').click();await expect(page.locator('.station-chart-v2')).toBeVisible();await page.locator('.hero-doors [data-room="listen"]').click();await expect(page.locator('#phasea-overlay')).toHaveAttribute('data-room','listen');await expect(page.locator('.listen-hero h2')).toContainText('ALGUIEN ESTÁ HABLANDO');await page.locator('[data-rnav="learn"]').click();await expect(page.locator('#phasea-overlay')).toHaveAttribute('data-room','learn');await expect(page.locator('.learning-route')).toBeVisible();const after=await geometry(page);expect(after.scrollHeight).toBe(before.scrollHeight);expect(after.bodyHeight).toBe(before.bodyHeight);expect(after.scrollWidth).toBeLessThanOrEqual(after.clientWidth)});
