const {test,expect}=require('@playwright/test');
test.setTimeout(180000);
const sceneIds=['hero','coast','keeper','stair','machine','beam','afterlight'];
async function openStory(page){await page.goto('/storytelling.html',{waitUntil:'domcontentloaded',timeout:45000});await page.waitForFunction(()=>window.__FARO_QA__?.ready===true,null,{timeout:60000});await page.waitForSelector('#support-trigger',{state:'attached'});await page.waitForTimeout(250)}
async function jump(page,id,f=.38){await page.evaluate(({id,f})=>{const e=document.getElementById(id);scrollTo(0,e.offsetTop+Math.min(e.offsetHeight*f,520))},{id,f});await page.waitForTimeout(550)}
async function geometry(page){return page.evaluate(sceneIds=>({scrollHeight:document.documentElement.scrollHeight,bodyHeight:document.body.scrollHeight,scrollWidth:document.documentElement.scrollWidth,clientWidth:document.documentElement.clientWidth,scenes:Object.fromEntries(sceneIds.map(id=>{const e=document.getElementById(id),r=e.getBoundingClientRect();return[id,{offsetTop:e.offsetTop,offsetHeight:e.offsetHeight,width:r.width,height:r.height}]})),supportInsidePage:!!document.querySelector('.page #support-trigger,.page #support-deck,.page #answer-event,.page #support-field-signal'),supportInsideSection:!!document.querySelector('.sec #support-trigger,.sec #support-deck,.sec #answer-event,.sec #support-field-signal')}),sceneIds)}
async function grantClipboard(page){await page.context().grantPermissions(['clipboard-read','clipboard-write']);}

test('Rule 0: support overlay never changes frozen Faro geometry or scroll position',async({page})=>{await page.setViewportSize({width:1440,height:1000});await openStory(page);await jump(page,'coast');const before=await geometry(page),y0=await page.evaluate(()=>scrollY);expect(before.supportInsidePage).toBeFalsy();expect(before.supportInsideSection).toBeFalsy();await expect(page.locator('#support-trigger')).toBeVisible();await expect(page.locator('#support-trigger')).toContainText('WEATHER INSIDE');await page.locator('#support-trigger').click();await expect(page.locator('#support-deck')).toHaveClass(/open/);const open=await geometry(page),yOpen=await page.evaluate(()=>scrollY);expect(open).toEqual(before);expect(yOpen).toBe(y0);await page.mouse.wheel(0,900);await page.waitForTimeout(150);expect(await page.evaluate(()=>scrollY)).toBe(y0);await page.locator('#support-close').click();await page.waitForTimeout(180);expect(await page.evaluate(()=>scrollY)).toBe(y0);const closed=await geometry(page);expect(closed).toEqual(before)});

test('Progressive reveal includes a moving field signal and intentional silence sections',async({page})=>{await page.setViewportSize({width:1440,height:1000});await openStory(page);await jump(page,'coast');await expect(page.locator('#support-trigger')).toBeVisible();await expect(page.locator('#support-trigger')).toContainText('WEATHER INSIDE');await expect(page.locator('#support-field-signal')).toHaveClass(/fly/);await jump(page,'keeper');await expect(page.locator('#support-trigger')).toBeHidden();await jump(page,'stair');await expect(page.locator('#support-trigger')).toContainText('ONE STEP');await expect(page.locator('#support-field-signal')).toHaveClass(/fly/);await jump(page,'machine');await expect(page.locator('#support-trigger')).toBeHidden();await jump(page,'beam');await expect(page.locator('#support-trigger')).toContainText('SEND A SIGNAL');await jump(page,'afterlight');await expect(page.locator('#support-trigger')).toContainText('ANOTHER STATION')});

test('Five actions: Fog → One Step → Signal → symbolic light → navigation beacons',async({page})=>{await grantClipboard(page);await page.setViewportSize({width:1440,height:1000});await openStory(page);await jump(page,'coast');await page.locator('#support-trigger').click();await expect(page.locator('#support-content')).toContainText('How is the weather inside?');await page.locator('[data-choice="fog"]').click();await expect(page.locator('.deck-result')).toContainText('next visible marker');await page.locator('#support-close').click();await jump(page,'stair');await page.locator('#support-trigger').click();await page.locator('[data-choice="tell"]').click();await expect(page.locator('.deck-result')).toContainText('I am having a hard time');await page.locator('#support-close').click();await jump(page,'beam');await page.locator('#support-trigger').click();await page.locator('[data-signal="listen"]').click();await expect(page.locator('.signal-template')).toContainText('Could you listen for a while?');await page.locator('#copy-signal').click();await expect(page.locator('#answer-event')).toHaveClass(/show/);await expect(page.locator('#answer-copy')).toContainText('A second light appears');await expect(page.locator('#answer-copy')).toContainText('symbolic');await expect(page.locator('#answer-copy')).toContainText('There was one light. Now there are two.');await expect(page.locator('.answer-beam.secondary')).toBeAttached();await page.waitForTimeout(2900);await page.locator('#answer-return').click();await jump(page,'afterlight');await page.locator('#support-trigger').click();await expect(page.locator('.station-chart-v2')).toBeVisible();await expect(page.locator('.station-node')).toHaveCount(5);await expect(page.locator('.station-card')).toHaveCount(0);for(let i=0;i<5;i++){await page.locator(`[data-station="${i}"]`).click();await expect(page.locator('#station-detail')).toContainText(['717 003 717','965 131 122','965 112 125','024','112'][i])}});

test('LISTEN is visible, has a live demo radio and richer listening formats',async({page})=>{await page.setViewportSize({width:1440,height:1000});await openStory(page);const before=await geometry(page);await jump(page,'afterlight');await page.locator('#support-trigger').click();await expect(page.locator('.hero-doors [data-room="listen"]')).toBeVisible();await page.locator('.hero-doors [data-room="listen"]').click();await expect(page.locator('#support-deck')).toHaveClass(/room-mode/);await expect(page.locator('#support-door-dock')).toBeVisible();await expect(page.locator('#support-content')).toContainText('Lighthouse Radio');await expect(page.locator('.radio-console')).toBeVisible();await expect(page.locator('#radio-toggle')).toContainText('PLAY LIVE');await expect(page.locator('#lighthouse-radio')).toHaveAttribute('src',/nightride\.fm\/chillsynth\.mp3/);await expect(page.locator('.listen-grid article')).toHaveCount(4);await expect(page.locator('.signal-strip button')).toHaveCount(3);await expect(page.locator('.session-list article')).toHaveCount(3);const after=await geometry(page);expect(after.scrollHeight).toBe(before.scrollHeight);expect(after.bodyHeight).toBe(before.bodyHeight)});

test('LEARN exposes four navigable micro-workshops with feedback',async({page})=>{await page.setViewportSize({width:1440,height:1000});await openStory(page);await jump(page,'afterlight');await page.locator('#support-trigger').click();await page.locator('.hero-doors [data-room="learn"]').click();await expect(page.locator('#support-content')).toContainText('Listening is a skill');await expect(page.locator('.workshop-nav button')).toHaveCount(4);await page.locator('[data-learn="stay"]').click();await expect(page.locator('.learn-result')).toContainText('opens space');await page.locator('[data-module="ask"]').click();await expect(page.locator('.workshop-stage')).toContainText('THE FIRST TEN WORDS');await page.locator('[data-learn="soft"]').click();await expect(page.locator('.learn-result')).toContainText('open question');await page.locator('[data-module="station"]').click();await expect(page.locator('.workshop-stage')).toContainText('BRING IN ANOTHER STATION')});

test('Mobile ES: moving signals, beacon chart, LISTEN/LEARN and zero horizontal break',async({page})=>{await page.setViewportSize({width:390,height:844});await openStory(page);const before=await geometry(page);await page.locator('[data-lang="es"]').click();await expect(page.locator('html')).toHaveAttribute('lang','es');await jump(page,'coast');await expect(page.locator('#support-trigger')).toContainText('TIEMPO');await expect(page.locator('#support-field-signal')).toHaveClass(/fly/);await page.locator('#support-trigger').click();await expect(page.locator('#support-content')).toContainText('¿Qué tiempo hace por dentro?');await page.locator('#support-close').click();await jump(page,'afterlight');await expect(page.locator('#support-trigger')).toContainText('OTRA ESTACIÓN');await page.locator('#support-trigger').click();await expect(page.locator('.station-chart-v2')).toBeVisible();await expect(page.locator('.hero-doors')).toContainText('02 · LISTEN');await expect(page.locator('.hero-doors')).toContainText('03 · LEARN');await page.locator('[data-station="2"]').click();await expect(page.locator('#station-detail')).toContainText('Proyecto Hombre');const after=await geometry(page);expect(after.scrollHeight).toBe(before.scrollHeight);expect(after.bodyHeight).toBe(before.bodyHeight);expect(after.scrollWidth).toBeLessThanOrEqual(after.clientWidth)});
