const {test,expect}=require('@playwright/test');
const fs=require('fs');
test.setTimeout(240000);
async function ready(page){await page.goto('/storytelling.html',{waitUntil:'domcontentloaded',timeout:45000});await page.waitForFunction(()=>window.__FARO_QA__?.ready===true&&window.__FARO_VISUAL_PREMIUM__?.installed===true,null,{timeout:60000});await page.waitForTimeout(900)}
async function jump(page,id,f=.42){await page.evaluate(({id,f})=>{const e=document.getElementById(id);scrollTo(0,e.offsetTop+Math.min(e.offsetHeight*f,620))},{id,f});await page.waitForTimeout(1200)}

test('desktop: keeper memory plate is feathered into the Faro world',async({page})=>{fs.mkdirSync('qa-artifacts/visual-premium',{recursive:true});await page.setViewportSize({width:1440,height:1000});await ready(page);await jump(page,'keeper',.34);await expect(page.locator('.keeper-window')).toBeVisible();const s=await page.locator('.keeper-plate').evaluate(el=>{const c=getComputedStyle(el);return{mask:c.maskImage||c.webkitMaskImage,opacity:Number(c.opacity),filter:c.filter,outline:getComputedStyle(el.parentElement).outlineStyle,section:document.body.dataset.premiumSection}});expect(s.mask).not.toBe('none');expect(s.opacity).toBeGreaterThan(.45);expect(s.filter).toContain('saturate');expect(s.outline).toBe('none');expect(s.section).toBe('keeper');await page.screenshot({path:'qa-artifacts/visual-premium/keeper-desktop.png',fullPage:false})});

test('desktop: Machine uses aligned sub-frustum instead of a disconnected second shot',async({page})=>{fs.mkdirSync('qa-artifacts/visual-premium',{recursive:true});await page.setViewportSize({width:1440,height:1000});await ready(page);await jump(page,'machine',.22);await expect(page.locator('.live-frame')).toBeVisible();await page.waitForFunction(()=>window.__FARO_VISUAL_PREMIUM__?.alignedFrames>3,null,{timeout:15000});const q=await page.evaluate(()=>({aligned:window.__FARO_VISUAL_PREMIUM__.alignedFrames,section:document.body.dataset.premiumSection,overflow:document.documentElement.scrollWidth-document.documentElement.clientWidth}));expect(q.aligned).toBeGreaterThan(3);expect(q.section).toBe('machine');expect(q.overflow).toBeLessThanOrEqual(1);await page.screenshot({path:'qa-artifacts/visual-premium/machine-aligned-desktop.png',fullPage:false})});

test('world depth layer adds coast, sea skin and atmosphere without adding another canvas',async({page})=>{await page.setViewportSize({width:1440,height:1000});await ready(page);const q=await page.evaluate(()=>({canvases:document.querySelectorAll('canvas#gl').length,overlay:!!document.querySelector('#premium-world'),rocks:!!window.__FARO_VISUAL_PREMIUM__?.scene?.getObjectByName('premium-coast-depth'),sea:!!window.__FARO_VISUAL_PREMIUM__?.scene?.getObjectByName('premium-sea-skin'),haze:!!window.__FARO_VISUAL_PREMIUM__?.scene?.getObjectByName('premium-atmospheric-haze')}));expect(q.canvases).toBe(1);expect(q.overlay).toBeTruthy();expect(q.rocks).toBeTruthy();expect(q.sea).toBeTruthy();expect(q.haze).toBeTruthy()});

test('mobile 390x844 keeps premium keeper and machine treatment inside viewport',async({page})=>{fs.mkdirSync('qa-artifacts/visual-premium',{recursive:true});await page.setViewportSize({width:390,height:844});await ready(page);await jump(page,'keeper',.28);await page.screenshot({path:'qa-artifacts/visual-premium/keeper-mobile.png',fullPage:false});await jump(page,'machine',.16);await page.waitForFunction(()=>window.__FARO_VISUAL_PREMIUM__?.alignedFrames>2,null,{timeout:15000});const q=await page.evaluate(()=>({sw:document.documentElement.scrollWidth,cw:document.documentElement.clientWidth,frame:document.querySelector('.live-frame')?.getBoundingClientRect().width||0}));expect(q.sw).toBeLessThanOrEqual(q.cw+1);expect(q.frame).toBeGreaterThan(100);await page.screenshot({path:'qa-artifacts/visual-premium/machine-mobile.png',fullPage:false})});
